# -*- coding: utf-8 -*-
"""Kindersendungen der Vollprogramme.

Erzeugt von scan_kinder.py aus tv.de am 22.08.2026. Auswahl nach Kategorie,
bekannten Titeln und Beschreibung; Alterswerte heuristisch.
"""

TAGE = [
    ("Samstag, 22.08.2026", "ARD", [
        ('07:05', 'Shaun das Schaf', 'Die Entführung', 'Zeichentrick', 10, 3, 'a3', 55, 'Ach, du Schreck! Beim morgendlichen Toilettengang entdeckt Shaun, dass der Fuchs den Hahn entführt h'),
        ('07:15', 'Anna im Land der tausend Seen', 'Der graue Wanderer', 'Vorlesen', 25, 3, 'a3', 55, 'Mit Rangerin Martina begibt sich Anna auf Wolfsspurensuche. Sie will herausfinden, welchen Einfluss '),
        ('07:55', 'Checker Tobi', 'Der Lecker-Schmecker-Check', 'Wissen', 25, 3, 'a3', 55, 'Für sein Lecker-Schmecker-Menü holt sich Tobi Rat bei Ernährungsexpertin Caro. Auf einem Wochenmarkt'),
        ('08:20', 'Wissen macht Ah!', 'Lumpi, platz!', 'Vorlesen', 25, 6, 'a6', 55, 'Platzende Würstchen, platzende Seifenblasen, platzender Lumpi - so oder ähnlich hatten Clarissa und '),
        ('08:45', 'POV - Deine Geschichte zählt', 'Hauptsache Crash vermeiden - Mein Leben mit ME/CFS', 'Vorlesen', 10, 6, 'a6', 55, 'Nach Covid verändert ME/CFS Neles Leben komplett. Wie lebt die 20-jährige mit Fatigue, Crashs und ei'),
        ('08:55', 'Die Pfefferkörner', 'Der Pralinenraub', 'Serie', 25, 10, 'a10', 55, 'Im Schokoladenmuseum wurde eingebrochen und die Tochter des Museumschefs, Anouk, ist spurlos verschw'),
        ('09:20', 'Die Pfefferkörner', 'Sven unter Verdacht', 'Serie', 30, 10, 'a10', 55, 'Nach einer anonymen Anzeige gerät Sven unter Verdacht, in seinem Imbiss mit Drogen zu dealen. Bei de'),
    ]),
    ("Samstag, 22.08.2026", "ZDF", [
        ('06:55', 'Die Biene Maja', 'Majas Blume', 'Zeichentrick', 10, 3, 'a3', 55, 'Maja hat eine außergewöhnliche Idee: Sie will für Willi eine wunderschöne Blume pflanzen. Aber das w'),
        ('07:05', 'Die Biene Maja', 'Die verwirrte Irma', 'Zeichentrick', 20, 3, 'a3', 55, 'Wie kann eine Sammelbiene alle verwirren? Die Lösung ist nicht einfach für Maja. Die Biene ist gar k'),
        ('07:25', 'Bibi Blocksberg', 'Die Mathekrankheit', 'Zeichentrick', 25, 3, 'a3', 55, 'Eine Klassenarbeit in Mathematik steht an. Bibi ist verzweifelt und bekommt prompt die Mathekrankhei'),
        ('07:50', 'Bibi Blocksberg', 'Der Superhexspruch', 'Zeichentrick', 25, 3, 'a3', 55, 'Die Neustädter Kinder haben große Sorgen: Die Bank will auf dem Schulhof bauen, es soll keine neuen '),
        ('08:15', 'Robin Hood - Schlitzohr von Sherwood', 'Feuer in Sherwood', 'Zeichentrick', 15, 6, 'a6', 55, 'Prinz John ärgert sich mal wieder über Robin und beschließt, den ganzen Wald niederbrennen zu lassen'),
        ('08:30', 'Robin Hood - Schlitzohr von Sherwood', 'Unsichtbare Diebe', 'Zeichentrick', 10, 6, 'a6', 55, 'Im Dorf verschwinden alle möglichen Schmuckstücke wie von Zauberhand. Auch Little John vermisst plöt'),
        ('08:40', 'H2O - Abenteuer Meerjungfrau', 'Erinnerungslücken', 'Zeichentrick', 25, 10, 'a10', 55, 'Nach einem Tag, an dem alles schiefgegangen ist, wünscht sich Cleo, sie könnte die ganze Meerjungfra'),
        ('09:05', 'Bibi und Tina', 'Die Schmugglerpferde', 'Zeichentrick', 25, 6, 'a6', 55, 'Bibi, Tina und Alex fahren zu den Sanders, die einen Reiterhof am Meer eröffnen. Die drei Freunde he'),
        ('09:30', 'Pippi Langstrumpf', 'Pippi und die Seeräuber (1)', 'Serie', 25, 6, 'a6', 55, 'Als die Eltern von Tommy und Annika verreisen, brechen drei herrliche Wochen an, die die Geschwister'),
        ('09:55', 'Pippi Langstrumpf', 'Pippi und die Seeräuber (2)', 'Serie', 25, 6, 'a6', 55, 'Auf ihrer Reise nach Taka-Tuka-Land müssen Pippi, Tommy und Annika auf einer unbekannten Palmeninsel'),
    ]),
    ("Samstag, 22.08.2026", "ProSieben Maxx", [
        ('06:40', 'Eyeshield 21', 'Der Gegenangriff des Teufels', 'Anime', 25, 12, 'a10', 55, 'Das Halbfinale zwischen den Devil Bats und den Wild Gunmen geht weiter und so auch das Duell zwische'),
        ('07:05', 'Eyeshield 21', 'Stolz und Lichtgeschwindigkeit', 'Anime', 25, 12, 'a10', 55, 'Es bleiben nur noch wenige Minuten im entscheidenden Halbfinale zwischen den Devil Bats und den Wild'),
        ('07:30', 'Die neuen Abenteuer des He-Man', 'Rockfieber', 'Zeichentrick', 25, 3, 'a3', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('07:55', 'Die neuen Abenteuer des He-Man', 'Dreadator, der Gefürchtete', 'Zeichentrick', 25, 3, 'a3', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:20', 'Die neuen Abenteuer des He-Man', 'Gefangen im Ionensturm', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:45', 'She-Ra', 'Das Schicksalstor', 'Zeichentrick', 25, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('09:10', 'She-Ra', 'Die Einhörner in Gefahr', 'Zeichentrick', 25, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('09:35', 'Voltron: Legendärer Verteidiger', 'Ursprung', 'Zeichentrick', 25, 6, 'a6', 55, 'In höchster Eile bricht Voltron nach Oriande auf, um Honervas durchtriebene Pläne zu durchkreuzen. M'),
        ('10:00', 'Voltron: Legendärer Verteidiger', 'Tag 47', 'Zeichentrick', 20, 6, 'a6', 55, 'In ihrem Vlog gewähren die Piloten Kinkade und Rizavi einen Einblick in den Alltag an Bord der Atlas'),
        ('10:20', 'She-Ra und die Rebellen-Prinzessinnen', 'Die Schlacht von Bright Moon', 'Zeichentrick', 25, 6, 'a6', 55, 'Die Kriegerin She-Ra will ihren Planeten aus den Fängen der Horde befreien.'),
        ('10:45', 'Die neuen Abenteuer des He-Man', 'Die Legende von Zil', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('11:10', 'Die neuen Abenteuer des He-Man', 'Der Ruf der Herde', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('11:35', 'Die neuen Abenteuer des He-Man', 'Das Innere des Vulkans', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('12:00', 'She-Ra', 'Der ehrgeizige Lehrling', 'Zeichentrick', 25, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('12:25', 'She-Ra', 'Zoogeschichten', 'Zeichentrick', 20, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('12:45', 'Voltron: Legendärer Verteidiger', 'Strahlentag', 'Zeichentrick', 25, 6, 'a6', 55, 'Die Atlas und die Löwen erreichen den Planeten Drazan, um an den Feierlichkeiten des Clear Day teilz'),
        ('13:10', 'Voltron: Legendärer Verteidiger', 'Ritter des Lichts (1)', 'Zeichentrick', 30, 6, 'a6', 55, 'Die Paladine sehen sich einer heiklen Aufgabe gegenüber: Angeführt von Allura dringen sie tief in Ho'),
        ('13:40', 'She-Ra und die Rebellen-Prinzessinnen', 'Der gefrorene Wald', 'Zeichentrick', 20, 6, 'a6', 55, 'Die Kriegerin She-Ra will ihren Planeten aus den Fängen der Horde befreien.'),
    ]),
    ("Samstag, 22.08.2026", "WDR", [
        ('07:55', 'Die Sendung mit dem Elefanten', 'Wofür hat ein Igel so viele Stacheln?', 'Serie', 25, 3, 'a3', 55, 'In der "Sendung mit dem Elefanten" gibt es heute eine spannende Tierdokumentation über einen Igel. D'),
        ('08:20', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 6, 'a6', 55, 'Lach- und Sachgeschichten'),
    ]),
    ("Samstag, 22.08.2026", "NDR", [
        ('07:00', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 3, 'a3', 55, '* Stadtschafe (Teil 3): Wie werden Schafe geschoren? Im dritten Teil der Sachgeschichte ist das Maus'),
    ]),
    ("Samstag, 22.08.2026", "MDR", [
        ('06:40', 'Meister Eder und sein Pumuckl', 'Pumuckl und Puwackl', 'Serie', 25, 3, 'a3', 55, 'Meister Eder kommt auf die Idee, von Pumuckl ein Abbild zu machen und schnitzt eine Holzpuppe. Misst'),
        ('07:05', 'Meister Eder und sein Pumuckl', 'Pumuckl und die Angst', 'Serie', 25, 3, 'a3', 55, 'Drei Kinder aus der Nachbarschaft von Meister Eder wollen Anja einen gehörigen Schrecken einjagen. A'),
        ('07:30', 'Ostwind - Aris Ankunft', '', 'Film', 95, 3, 'a3', 55, 'Als Mika den Hengst Ostwind vor einem Feuer retten will, wird sie schwer verletzt und fällt ins Koma'),
        ('18:54', 'Unser Sandmännchen', '', 'Serie', 6, 3, 'a3', 55, 'Pitti hat zwei Eiswaffeln und möchte sie nicht mit Schnattchen und Moppi teilen. Er versteckt sie de'),
    ]),
    ("Samstag, 22.08.2026", "RBB", [
        ('09:00', 'Dornröschen', '', 'Serie', 70, 6, 'a6', 55, 'Anläßlich der Geburt ihrer Tochter geben König und Königin ein großes Fest. Geladen sind auch zwölf '),
        ('10:10', 'Der Froschkönig', '', 'Serie', 60, 6, 'a6', 55, 'Prinzessin Sophie wird 18 Jahre alt. Salutschüsse, jubelnde Prinzen und Prinzessinnen, ein strahlend'),
        ('11:10', 'Die wahnsinnig traurige Prinzessin', '', 'Serie', 70, 6, 'a6', 55, 'Zwei Königreiche, zwei Könige; der eine hat einen Thronfolger, der andere eine einzige Tochter als E'),
        ('12:20', 'Das tapfere Schneiderlein', '', 'Serie', 80, 6, 'a6', 55, '"Sieben auf einen Streich" steht auf dem Gürtel. Alle sollen erfahren, was er für ein Kerl ist. Der '),
        ('13:40', 'Die Gänsehirtin am Brunnen', '', 'Serie', 55, 6, 'a6', 55, 'Hans zieht in die Welt, um Macht und Reichtum zu gewinnen. Eine Fee erfüllt seine maßlosen Erwartung'),
        ('14:35', 'Prinzessin Maleen', '', 'Serie', 60, 6, 'a6', 55, 'Prinzessin Maleen liebt den wenig standesgemäßen Landgrafen Konrad. Ihr Vater aber hat andere Pläne:'),
        ('15:35', 'Wie man Prinzessinnen weckt', '', 'Serie', 80, 6, 'a6', 55, 'Als dem Herrscherpaar des Rosenkönigreiches eine Tochter geboren wird, ist die Freude groß. Doch das'),
        ('16:55', 'Tischlein deck dich', '', 'Serie', 58, 6, 'a6', 55, 'Von der gefräßigen Ziege veräppelt und von kaum jemandem ernst genommen, will Max seinem Vater und d'),
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Pittiplatsch: Zwei Eiswaffeln im Briefkasten'),
    ]),
    ("Samstag, 22.08.2026", "HR", [
        ('08:45', 'Schau in meine Welt', 'Lina die Boxerin aus der Wüste', 'Vorlesen', 25, 6, 'a6', 55, 'Lina (12) aus Jordanien trainiert seit einem Jahr im Boxring und ist bereits so erfolgreich, dass es'),
    ]),
    ("Samstag, 22.08.2026", "ORF 1", [
        ('06:55', 'Grizzy und die Lemminge', 'Die gestohlene Fernbedienung', 'Zeichentrick', 8, 3, 'a3', 55, 'Grizzy möchte es sich richtig gemütlich machen. Er bereitet ein gutes Mahl vor und will sich eine TV'),
        ('07:03', 'Dora', 'Das Große Grandma-Wettkochen / Wo ist Map?', 'Zeichentrick', 22, 3, 'a3', 55, 'Das Große Grandma-Wettkochen: Das große Wettkochen der Grandmas steht an, aber als Doras Großmutter '),
        ('07:25', 'Helmi-Kinder-Verkehrs-Club', 'Cool, cooler am coolsten', 'Wissen', 5, 3, 'a3', 55, 'Samy findet den älteren Skateboarder Rodo voll cool. Samy zieht sich so an wie Rodo und übt in jeder'),
        ('07:30', 'ABC Bär', '', 'Vorlesen', 15, 3, 'a3', 55, 'Der ABC Bär und seine Tierfreunde reisen mit ihrem lustigen Baumhaus durch das Land, um ihre Zahl- u'),
        ('07:45', 'Kung Fu Panda: Die Tatzen des Schicksals', 'Die Rückkehr der vier Konstellationen', 'Zeichentrick', 22, 3, 'a3', 55, 'Po und seine Schülerinnen und Schüler finden beim Hasen Bunnidharma Unterschlupf. Bei ihm nehmen sie'),
        ('08:07', 'Box', 'Kochen', 'Wissen', 5, 6, 'a6', 55, 'Unser heutiges Motto: Beste Reste - wir zeigen euch, wie ihr aus übriggebliebenen Lebensmitteln köst'),
        ('08:12', 'Tom Turbo', 'Die Monstermaske', 'Serie', 26, 6, 'a6', 55, 'Die interaktive Krimi-Serie von Thomas Brezina mit spannenden Detektivtipps zum Nachmachen und unter'),
        ('08:54', 'Cyber Kids', 'Influencer', 'Wissen', 17, 6, 'a6', 55, 'Wie erkennt man Werbung im Internet? Zoa ist super aufgeregt: Ihre Lieblings-Influencerin schwärmt o'),
        ('09:11', 'Der gestiefelte Kater - Abenteuer in San Lorenzo', 'Eine Katze für die Hexe', 'Serie', 23, 6, 'a6', 55, 'Mit Hut und Degen zieht der gestiefelte Kater durchs Land, immer auf der Suche nach einem neuen Aben'),
        ('09:34', 'Tanzen mit den Stars', 'HipHop mit Dimitar Stefanin', 'Vorlesen', 18, 6, 'a6', 55, "Heute gibt's bei Tanzen mit den Stars coole Moves im HipHop mit Dimitar Stefanin. Die Tanzkinds dürf"),
        ('09:52', 'Klimakrach', 'Wilde Natur', 'Wissen', 16, 6, 'a6', 55, 'In dieser Folge widmen sich Clara und Waldemar dem Wunder Wildnis. Waldemar hat einen Staubsauger er'),
        ('10:08', 'Dragons - Die Wächter von Berk', 'Raffnuss, die Drachenzähmerin', 'Zeichentrick', 22, 6, 'a6', 55, 'Hicks und seine Freunde entdecken auf einer Insel einen verletzten Wasserdrachen. Er kann nicht zurü'),
        ('10:30', '1000 Tricks', '', 'Vorlesen', 16, 6, 'a6', 55, 'Heute gehen Melly und Christoph auf eine Foto-Safari in den Tiergarten. Ein gesunder Snack darf dabe'),
        ('10:46', 'Ganz Ohr', 'Adrenalin', 'Vorlesen', 18, 6, 'a6', 55, 'Warum fahren manche Kinder gern Achterbahn, wilde Karusselle oder Geisterbahnen und andere nicht? Un'),
        ('11:04', 'Vegesaurier', 'Im Nest', 'Zeichentrick', 6, 6, 'a6', 55, 'Gingers größter Wunsch wäre es, fliegen zu können. Obwohl sie gar keine Flügel hat, unternimmt das T'),
        ('11:10', 'Galapagos X', 'Der Roboter-Tanz-Wettbewerb', 'Zeichentrick', 11, 6, 'a6', 55, 'In der Zukunft herrscht Ressourcenknappheit, denn die Menschen haben alles Öl und Gas verbrannt. Des'),
    ]),
    ("Samstag, 22.08.2026", "SRF 1", [
        ('09:00', 'Kassensturz in Gebärdensprache', 'Risiko Online-Rezept - Medikamente ohne Arztbesuch', 'Serie', 35, 6, 'a6', 55, 'Risiko Online-Rezept - Medikamente ohne Arztbesuch Keine Lust aufs Wartezimmer, auf einen Arztbesuch'),
        ('10:30', 'SRF Kids Inside', 'Ein bisschen gefährlicher als singen: Ab ins Kanu!', 'Vorlesen', 10, 6, 'a6', 55, 'Ein Verein, vier Kids und noch mehr Storys: «SRF Kids Inside» erzählt Geschichten mitten aus dem Leb'),
        ('10:40', 'SRF Kids Inside', 'Aufnahmeprüfung Musicalschule - Next stop: Broadway New York?', 'Vorlesen', 15, 6, 'a6', 55, 'Ein Verein, vier Kids und noch mehr Storys: «SRF Kids Inside» erzählt Geschichten mitten aus dem Leb'),
        ('10:55', 'SRF Kids', '#SayHi 2026 - Zu Besuch bei den Songaufnahmen von «Alli zäme» ?', 'Vorlesen', 5, 6, 'a6', 55, 'Was ist #SayHi? Jedes Jahr folgen Tausende Kinder dem Aufruf von SRF Kids, zum #SayHi-Song gegen Mob'),
        ('17:40', 'Minisguard', 'Wie bleiben Lebensmittel länger frisch?', 'Serie', 20, 6, 'a6', 55, 'Auf der Suche nach Antworten besucht Élin Ana, Expertin für Lebensmittellagerung bei Valentin Gastro'),
    ]),
    ("Sonntag, 23.08.2026", "ARD", [
        ('05:30', 'HipHorses - Du und Dein Pferd', 'Aileen und die Minipferde Nellie, Donna & Co.', 'Vorlesen', 25, 3, 'a3', 55, 'Aileen aus Leipzig liebt ihre amerikanischen Miniaturpferde Nellie, Donna, & Co. über alles. Nach ih'),
        ('06:10', 'Tigerenten Club', 'Der Club zum Mitmachen - Spiele, Spaß und spannendes Wissen', 'Vorlesen', 55, 3, 'a3', 55, 'Als Astronautin ins All! Anschnallen - es geht ins Weltall! Amelie wird zur Astronautin ausgebildet.'),
        ('08:30', 'Alina', 'Silverado in Gefahr', 'Jugendserie', 60, 10, 'a10', 55, 'Alina heißt das 13-jährige Mädchen, das im Mittelpunkt des Dreiteilers steht. Die Schülerin lebt mit'),
        ('09:30', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 6, 'a6', 55, 'Lach- und Sachgeschichten, heute mit einer Gottesanbeterin auf der Lauer, einem großen Monster im Wa'),
    ]),
    ("Sonntag, 23.08.2026", "ZDF", [
        ('06:00', 'Die Werkel-Ferkel', 'Schlummerpause', 'Zeichentrick', 10, 3, 'a3', 55, 'Der Hase Rüdi bringt seine Häschen-Rasselbande immer mit einem Mobile zur Ruhe. Dumm nur, wenn diese'),
        ('06:10', 'Die Werkel-Ferkel', 'Äpfel für Alle', 'Zeichentrick', 15, 3, 'a3', 55, 'Die Werkel-Ferkel reparieren zusammen mit dem Ziegenjungen Kris einen kaputten Zaun. Aber irgendjema'),
        ('06:25', 'Sam & Julia im Mäusehaus', 'Die Herausforderung', 'Zeichentrick', 5, 3, 'a3', 55, 'Sam und Julia spielen sehr gerne zusammen. Ella und Tonio behaupten, sie könnten es nicht mal ein pa'),
        ('06:30', 'Sam & Julia im Mäusehaus', 'Die besondere Stricknadel', 'Zeichentrick', 10, 3, 'a3', 55, 'Sam und Julia langweilen sich schrecklich. Heute will ihnen einfach kein schönes Spiel einfallen. Da'),
        ('06:40', 'Sam & Julia im Mäusehaus', 'Der Schnurrhaar-Kamm', 'Zeichentrick', 5, 3, 'a3', 55, 'Sams Mutter möchte Sams Schnurrhaare kämmen, aber er kann das nicht leiden und läuft davon. Julia tr'),
        ('06:45', 'Pettersson und Findus', 'Ein Feuerwerk für den Fuchs', 'Zeichentrick', 15, 3, 'a3', 55, 'Pettersson und Findus müssen handeln - der alte Fuchs hat es auf die Hühner des Hofes abgesehen. Gem'),
        ('07:00', 'Wickie und die starken Männer', 'Die verflixte Kuh', 'Zeichentrick', 10, 3, 'a3', 55, 'Was tun, wenn eine Kuh Halvars Hochzeitsgeschenk für Ylva aufgefressen hat? Die Zeit wird knapp, abe'),
        ('07:10', 'Wickie und die starken Männer', 'Pilzesammeln', 'Zeichentrick', 15, 3, 'a3', 55, 'Wickie geht mit Ylvi Pilze sammeln, und da Gilby den gleichen Auftrag von seiner Mutter hat, geht er'),
        ('07:25', 'Bibi Blocksberg', 'Kreuzfahrt mit Oma Grete', 'Zeichentrick', 25, 3, 'a3', 55, 'Oma Grete und Bibi machen eine Kreuzfahrt. Auch eine Gräfin und deren Enkel Karl-Friedrich gehen an '),
        ('07:50', 'Bibi und Tina', 'Das Schlossfest', 'Zeichentrick', 25, 3, 'a3', 55, 'Der Graf hat zu einem Familientreffen auf Schloss Falkenstein eingeladen. Dort sollen die Familienmi'),
        ('08:15', 'Löwenzahn', 'Haut - Empfindlich auf die Pelle gerückt', 'Serie', 25, 6, 'a6', 55, 'Fritz Fuchs testet teures Haarwuchsmittel. Seine Schwester Suse hat es bei einem Straßenhändler geka'),
        ('08:40', 'Michel aus Lönneberga', 'Als Michel die Tiere mit Kirschen fütterte', 'Serie', 23, 6, 'a6', 55, 'Michels Mutter setzt Kirschwasser an, und Michel verfüttert die Kirschen an die Tiere. Schon bald la'),
    ]),
    ("Sonntag, 23.08.2026", "ProSieben Maxx", [
        ('04:10', 'Dr. STONE', 'Medusas wahres Gesicht', 'Anime', 20, 12, 'a10', 55, 'Mithilfe der Entsteinerungsflüssigkeit gelingt es Senku und seinen Freunden, Kaseki wiederzubeleben.'),
        ('04:30', 'One Piece', 'Ein massiver Gegenangriff - De Flamingos Erwachen!', 'Anime', 25, 12, 'a10', 55, 'Ruffy greift De Flamingo an, doch der Shichibukai blockiert die Attacke und reagiert mit einer verst'),
        ('04:55', 'One Piece', 'Ruffys Trumpf - Die Leo-Bazooka!', 'Anime', 25, 12, 'a10', 55, 'De Flamingo hat die Oberhand im Kampf gegen Ruffy, doch dieser holt zu einem massiven Gegenschlag au'),
    ]),
    ("Sonntag, 23.08.2026", "NDR", [
        ('05:00', 'Apple Hills', 'Der Autogrammjäger', 'Zeichentrick', 5, 3, 'a3', 55, 'In Apple Hills wurde der Popstar Lady Glitterstyle gesichtet. Alle wollen ein Autogramm von ihr. Auß'),
        ('05:05', 'Apple Hills', 'Das Monster aus dem Steinbruch', 'Zeichentrick', 5, 3, 'a3', 55, 'Lizzie muss für einen Wettbewerb ein Foto von einem seltenen Vogel machen. Aber als Trafalgar den Vo'),
        ('05:10', 'Apple Hills', 'Fahrrad des Todes', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar und Pulver verwandeln ein altes Fahrrad in eine Achterbahn. Aber als ihr Freund vom Fahrra'),
        ('05:15', 'Apple Hills', 'Die Statue von Herrn Zement', 'Zeichentrick', 5, 3, 'a3', 55, 'Herr Zement möchte einen wichtigen Kunden beeindrucken und beschließt, eine Statue von sich selbst a'),
        ('05:20', 'Apple Hills', 'Ein nebliges Spiel', 'Zeichentrick', 10, 3, 'a3', 55, 'Trafalgar und die anderen Kinder aus Apple Hills spielen im Finale des lokalen Fußballturniers. Aber'),
        ('05:30', 'Apple Hills', 'Walters dummer Hund', 'Zeichentrick', 5, 3, 'a3', 55, 'Um zu beweisen, dass sein sehr dummer Hund eigentlich sehr weise ist, lockt Cousin Walter Trafalgar '),
        ('05:35', 'Apple Hills', 'Der Phantomfriseur', 'Zeichentrick', 5, 3, 'a3', 55, 'Alle Kinder sind sehr glücklich mit ihren Frisuren. Aber als ein geheimer Friseur ihnen nachts die H'),
        ('05:40', 'Apple Hills', 'Die Geisterstadt', 'Zeichentrick', 5, 3, 'a3', 55, 'Herr Apfelberg möchte einen Geist fangen. Aber Trafalgar sagt, dass es in Apple Hills keine Geister '),
        ('05:45', 'Apple Hills', 'Die Mittelalter-Krise', 'Zeichentrick', 5, 3, 'a3', 55, 'Als Trafalgars Lehrerin Frau Olsen entdeckt, dass sie eine Nachfahrin von Königin Margrethe I. ist, '),
        ('05:50', 'Apple Hills', 'Super Opa', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar und Powder spielen Superhelden. Als sie hören, dass der alte Mann im Park eigentlich ein g'),
        ('05:55', 'Apple Hills', 'Saure Milch', 'Zeichentrick', 5, 3, 'a3', 55, 'Lizzie hasst Keime. Deshalb muss beim Einkauf für ihre Mutter alles desinfiziert werden. Doch durch '),
        ('06:00', 'Apple Hills', 'Der Club der Coolen', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar und Powder möchten Mitglieder des Clubs der Coolen werden. Aber sie können dem Club nicht '),
        ('06:05', 'Apple Hills', 'Der Korken', 'Zeichentrick', 5, 3, 'a3', 55, 'Die Zementfabrik hat den kleinen See in Apple Hills verschmutzt, sodass nun niemand mehr darin schwi'),
        ('06:10', 'Apple Hills', 'Der Traumkuchen', 'Zeichentrick', 5, 3, 'a3', 55, 'Jede Nacht träumt Trafalgar von Kuchen. Aber gerade, als er den Kuchen essen will, wacht er auf und '),
        ('06:15', 'Apple Hills', 'Die Nachrichten der Zukunft', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar versucht, eine Zeitung mit dem Titel "Die Nachrichten der Zukunft" zu verkaufen. Die besor'),
        ('06:20', 'Apple Hills', 'Die Frühstücksblöcke von Herrn Zement', 'Zeichentrick', 5, 3, 'a3', 55, 'Das Betongeschäft läuft schlecht, also beschließt Herr Zement, stattdessen zuckerhaltige Cerealien z'),
        ('06:25', 'Apple Hills', 'Stiefvaters Donnerschlag', 'Zeichentrick', 5, 3, 'a3', 55, 'Powders Stiefvater prahlt damit, dass er einmal den weltbesten Schlagmann im Baseball geschlagen hat'),
        ('06:30', 'Apple Hills', 'Ein Gewinnlos, bitte!', 'Zeichentrick', 10, 3, 'a3', 55, 'Beim jährlichen Apple Hills Festival wollen einige Kriminelle alle Lose für die große Goldene-Apfel-'),
        ('06:40', 'Apple Hills', 'Der lustige Onkel Knut', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgars Großmutter feiert ihren 90. Geburtstag, aber Onkel Knut findet, dass die Party etwas mehr'),
        ('06:45', 'Apple Hills', 'Papierflieger', 'Zeichentrick', 5, 3, 'a3', 55, 'Der neue Trend unter den Kindern in Apple Hills ist das Werfen von Papierfliegern. Da die Mädchen je'),
        ('06:50', 'Edgar, das Super-Karibu', 'Komplizierte Wörter', 'Zeichentrick', 10, 3, 'a3', 55, 'Birgit, die Journalistin führt eine Umfrage im Städtchen durch und kommt schnell zu der Ansicht, das'),
        ('07:00', 'Edgar, das Super-Karibu', 'Der Gemüse-Tag', 'Zeichentrick', 10, 3, 'a3', 55, 'Edgar, das Super-Karibu und Katja, die Katze, die ständig herumfaucht, versuchen die Bewohner des St'),
    ]),
    ("Sonntag, 23.08.2026", "BR", [
        ('08:35', 'Helene, die wahre Braut', '', 'Serie', 60, 6, 'a6', 55, 'Helene wird von ihrer bösen Stiefmutter Gertrud zu Arbeiten gezwungen, die nicht zu schaffen sind. A'),
    ]),
    ("Sonntag, 23.08.2026", "SWR", [
        ('11:00', 'Ostwind', '', 'Film', 95, 6, 'a6', 55, 'Die vierzehnjährige Mika muss ausgerechnet auf dem Reiterhof ihrer strengen Großmutter den Sommer üb'),
    ]),
    ("Sonntag, 23.08.2026", "MDR", [
        ('15:50', 'Der Schweinehirt', '', 'Serie', 60, 6, 'a6', 55, 'Das kleine Königreich Lichterwald steht vor dem finanziellen Ruin. Einzig und allein eine reiche Hoc'),
        ('18:52', 'Unser Sandmännchen', '', 'Serie', 8, 3, 'a3', 55, 'Herr Fuchs findet auf einem Abendspaziergang eine Kindergeldbörse, die er gern für sich behalten möc'),
    ]),
    ("Sonntag, 23.08.2026", "RBB", [
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Kallis Gute-Nacht-Geschichten: Kalli - Kalli'),
    ]),
    ("Sonntag, 23.08.2026", "arte", [
        ('04:45', 'Athleticus', 'Breakdance', 'Zeichentrick', 15, 3, 'a3', 55, 'Ein paar Seelöwen und Kängurus aus dem Viertel liefern sich ein Streetdance-Duell und zeigen einande'),
    ]),
    ("Sonntag, 23.08.2026", "ORF 1", [
        ('06:00', 'Tom - Ein echter Freund', 'Tom in Venedig', 'Zeichentrick', 25, 3, 'a3', 55, 'Mrs. Hamiltons Zirkus gastiert zur Zeit des Karnevals in Venedig. Dort lernen Tom und seine Freunde '),
        ('06:25', 'Vegesaurier', 'Baby Gurke', 'Zeichentrick', 5, 3, 'a3', 55, 'Die Gurkodile müssen sich sehr beeilen, als sie von einem Gewässer zu einem anderen wandern. Weil si'),
        ('06:30', 'Servus Kasperl', 'Kasperl & Leopold: Die verschwundene Zahnbürste', 'Serie', 25, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:55', 'Vegesaurier', 'Wo schlafen wir heute?', 'Zeichentrick', 5, 3, 'a3', 55, 'Ginger und die Erbs-Rex-Babys haben es nicht vor Einbruch der Nacht nach Hause geschafft und müssen '),
        ('07:00', 'Vegesaurier', 'Reingefallen!', 'Zeichentrick', 5, 3, 'a3', 55, 'Ginger und ihre Erbs-Rex-Babys fliehen vor zwei Bananaraptoren. Als diese in eine Grube fallen, besc'),
        ('07:05', 'Bakabu', 'Ich nicht', 'Vorlesen', 4, 3, 'a3', 55, 'Hast du schon einmal ein Eis gegessen, das nach Ketchup schmeckt oder im Schokokuchen eine Kuh entde'),
        ('07:09', 'Knall genial', '', 'Wissen', 19, 3, 'a3', 55, "Originelle Tipps und Tricks von Thomas Brezina und den Kids! Thomas' Kuriositätenladen ist wieder ge"),
        ('07:28', 'Der gestiefelte Kater - Abenteuer in San Lorenzo', 'Nur geträumt!', 'Serie', 22, 3, 'a3', 55, 'Mit Hut und Degen zieht der gestiefelte Kater durchs Land, immer auf der Suche nach einem neuen Aben'),
        ('07:50', 'Drunter & drüber mit Christoph Hirschler', 'NOA und der Dinosaurier in der Achterbahn', 'Vorlesen', 16, 3, 'a3', 55, 'Heute wird es bei "Drunter & Drüber" musikalisch! Christoph Hirschler und seine Band begrüßen den ju'),
        ('08:06', 'Campsite', 'Silje in der Patsche', 'Jugendserie', 10, 10, 'a10', 55, 'Silje erzählt ihren Freunden, dass sie den bekannten Influencer Kattekryp kennt und gut mit ihm befr'),
        ('08:16', 'Campsite', 'Der Trampolin-Streit', 'Jugendserie', 7, 10, 'a10', 55, 'Thea, Theo und Nura wollen Trampolin springen. Als sie beim Trampolin ankommen, sind sie verwundert,'),
        ('08:23', 'Campsite', 'Es gibt Krieg', 'Jugendserie', 8, 10, 'a10', 55, 'Der erbitterte Krieg ums Trampolin geht in die nächste Runde. Die beiden Lager um Nura und Andrine w'),
        ('08:31', 'Dragons - Die Wächter von Berk', 'Eingefroren', 'Zeichentrick', 22, 6, 'a6', 55, 'Als Hicks und Ohnezahn von einem Auftrag zurückkehren, finden sie zu ihrer Verwunderung Berk völlig '),
        ('08:53', 'Was geht?', 'Zusammen stark', 'Wissen', 13, 6, 'a6', 55, 'Eine starke Gemeinschaft - wie geht das? Tiara (10), Raffael (10) und Lou (10) sprechen mit Pädagogi'),
        ('09:06', 'Mini Spezial', 'Autodesigner', 'Vorlesen', 4, 6, 'a6', 55, 'Hast du schon mal ein Auto aus Plastilin gesehen, das gleich groß ist, wie Autos, die auf der Straße'),
        ('09:10', 'Garfield', 'Garfield im Land der Träume', 'Zeichentrick', 13, 6, 'a6', 55, 'Der Nachbarsjunge ist sehr erfinderisch und talentiert im Bau von wissenschaftlichen Maschinen. So h'),
        ('09:23', 'Hallo, was machst Du?', 'Gärtner', 'Wissen', 12, 6, 'a6', 55, 'Blumen pflanzen und Rasenmähen - das sind die Aufgaben von Gärtnerinnen und Gärtner, an die wahrsche'),
    ]),
    ("Sonntag, 23.08.2026", "SRF 1", [
        ('17:10', 'Minisguard', 'Wie bleiben Lebensmittel länger frisch?', 'Serie', 15, 6, 'a6', 55, 'Auf der Suche nach Antworten besucht Élin Ana, Expertin für Lebensmittellagerung bei Valentin Gastro'),
    ]),
    ("Montag, 24.08.2026", "ProSieben Maxx", [
        ('16:40', 'Dr. STONE', 'Kampf mit Köpfchen', 'Anime', 25, 12, 'a10', 55, 'Senku und seinen Kameraden gelingt es, immer mehr ihrer Freunde wiederzubeleben. Doch die Freude im '),
        ('17:05', 'Dragon Ball Super', 'Total außer Kontrolle! Eine wilde Berserkerin erwacht!', 'Anime', 25, 12, 'a10', 55, 'Son Goku trifft auf Caulifla und Kale, zwei Kämpferinnen aus dem sechsten Universum. Als Kale in ihr'),
        ('17:30', 'Detektiv Conan', 'Der verschwundene Polizist', 'Anime', 30, 12, 'a10', 55, 'Die Detective Boys treffen auf Ayumis ehemalige Nachbarin. Die Frau berichtet den Kindern von einem '),
        ('18:00', 'One Piece', 'Ausbreitende Schockwelle - Die schlimmste Generation tritt in Aktion!', 'Anime', 25, 12, 'a10', 55, 'Nach dem Kampf auf Dressrosa löst Kyros die Tontatta- Armee auf. Sakazuki trifft in Mary Geoise die '),
        ('18:25', 'One Piece', 'Die Geburt einer Legende! - Die Abenteuer des Revolutionskämpfers Sabo', 'Anime', 30, 12, 'a10', 55, "Die tapferen Kämpfer ruhen sich in Kyros' Haus aus. Bald stößt auch Sabo dazu, der etwas zu offenbar"),
        ('18:55', 'Detektiv Conan', 'Der mysteriöse Scharfschütze (2)', 'Anime', 25, 12, 'a10', 55, 'Yukiko, die Sekretärin von Direktor Ishimoto, hat einen Liebhaber namens Shibata, auf den Kogoro eif'),
    ]),
    ("Montag, 24.08.2026", "WDR", [
        ('06:45', 'Wissen macht Ah!', 'Wissen macht anziehend', 'Vorlesen', 25, 3, 'a3', 55, 'Farben und Muster - darum geht es in der heutigen Sendung. Denn Farben und Muster sind anziehend. Be'),
        ('07:10', 'POV - Deine Geschichte zählt', 'Hauptsache Crash vermeiden · Mein Leben mit ME/CFS', 'Vorlesen', 10, 3, 'a3', 55, 'Leonie (16) fühlt sich in der Schule oft ausgeschlossen. Halt findet sie in Musik, Konzerten und Onl'),
        ('07:20', 'Campsite', 'Wollen wir wetten?', 'Jugendserie', 10, 3, 'a3', 55, 'Klaus überredet William zu einer Runde Finger-Klatschen: Der Verlierer muss EINE Sache für den ander'),
        ('07:30', 'Campsite', 'Der Lottoschein', 'Jugendserie', 5, 3, 'a3', 55, 'Klaus, Max und Silje wollen eigentlich baden gehen, als Anja sie aufgeregt zu Ruth ruft - einer skur'),
        ('07:35', 'Campsite', 'Mafia', 'Jugendserie', 10, 3, 'a3', 55, 'William ist plötzlich ein Star auf dem Campingplatz. Der Grund: Er besitzt ein mysteriöses Foto, das'),
        ('07:45', 'Hauptsache Bären!', '', 'Serie', 85, 3, 'a3', 55, 'Jips großer Traum wird wahr, als ihre Eltern beschließen, in einem Wohnmobil durch Amerika zu reisen'),
    ]),
    ("Montag, 24.08.2026", "MDR", [
        ('18:54', 'Unser Sandmännchen', '', 'Serie', 6, 3, 'a3', 55, 'MiWau hört im Leckerladen ein mysteriöses Brummen. Moppi soll helfen, das unbekannte Geräusch zu erk'),
    ]),
    ("Montag, 24.08.2026", "RBB", [
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Moppi und MiWau: Der mutige Wachhund'),
    ]),
    ("Montag, 24.08.2026", "HR", [
        ('05:20', 'Schau in meine Welt', 'Lina die Boxerin aus der Wüste', 'Vorlesen', 25, 3, 'a3', 55, 'Lina (12) aus Jordanien trainiert seit einem Jahr im Boxring und ist bereits so erfolgreich, dass es'),
        ('06:35', 'Leo da Vinci', 'Die Fossilien-Höhle', 'Zeichentrick', 10, 3, 'a3', 55, 'Durch die holprige Straße hat sich die Bremse in Leos Gefährt gelöst. In der Nähe des nächsten Dorfe'),
        ('06:45', 'Leo da Vinci', 'Zwei Löwen', 'Zeichentrick', 15, 3, 'a3', 55, 'Die Gauner Robert und Jack sind verzweifelt. Die Karte, die sie nach Venedig und auf die Spur Leos z'),
    ]),
    ("Montag, 24.08.2026", "arte", [
        ('04:30', 'Athleticus', 'Fitness-Coach', 'Zeichentrick', 40, 3, 'a3', 55, 'Im Park coacht ein hartnäckiger Vogel Strauß einen behäbigen Elefanten beim Sport. Es gibt Lauftrain'),
    ]),
    ("Montag, 24.08.2026", "ORF 1", [
        ('06:05', 'Wickie und die starken Männer', 'Das böse Weib', 'Zeichentrick', 25, 3, 'a3', 55, 'Auf dem Heimweg nach Flake bekommen die Wikinger die Rache der Magyaren zu spüren: Ein starker Gegen'),
        ('06:30', 'Servus Kasperl', 'Kasperl & Hopsi: Der goldene Kerzenleuchter', 'Serie', 25, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:55', 'Die Jagd nach dem Kju Wang', 'Ardelias Foto-Termin', 'Zeichentrick', 25, 3, 'a3', 55, 'Yagor hat wiedereinmal einen Plan. Unter dem Decknamen Knipsi Bertolini, seines Zeichens berühmter P'),
        ('07:35', 'Vegesaurier', 'Im Nest', 'Zeichentrick', 5, 3, 'a3', 55, 'Gingers größter Wunsch wäre es, fliegen zu können. Obwohl sie gar keine Flügel hat, unternimmt das T'),
        ('07:40', 'Vegesaurier', 'Frische Kartoffelchips', 'Zeichentrick', 5, 3, 'a3', 55, 'Sonntags baden die Kartofflodons in den mineralreichen Quellen und aalen sich daraufhin in der Sonne'),
        ('07:45', 'Dragons - Die Wächter von Berk', 'Raffnuss, die Drachenzähmerin', 'Zeichentrick', 20, 3, 'a3', 55, 'Hicks und seine Freunde entdecken auf einer Insel einen verletzten Wasserdrachen. Er kann nicht zurü'),
    ]),
    ("Montag, 24.08.2026", "SRF 1", [
        ('17:30', 'Kiri und Lou', 'Immer wider Versteckis', 'Zeichentrick', 10, 6, 'a6', 55, 'Kiri und Lou, zwei junge Dinosaurier, leben in einem wunderschönen Wald. Die beiden ungleichen Freun'),
    ]),
]
