# -*- coding: utf-8 -*-
"""Kindersendungen der Vollprogramme.

Erzeugt von scan_kinder.py aus tv.de am 07.08.2026. Auswahl nach Kategorie,
bekannten Titeln und Beschreibung; Alterswerte heuristisch.
"""

TAGE = [
    ("Freitag, 07.08.2026", "ProSieben", [
        ('09:05', 'The Middle', 'Die Gebrüder Heck', 'Serie', 25, 6, 'a6', 55, 'Frankie und Mike planen einen romantischen Abend zu zweit. Zur Einstimmung leihen sie sich einen Fil'),
    ]),
    ("Freitag, 07.08.2026", "ProSieben Maxx", [
        ('16:40', 'Dr. STONE', 'Erster Kontakt', 'Anime', 25, 12, 'a10', 55, 'Für das Schiff, das die Mannschaft nach Südamerika bringen soll, benötigt Senku Erdöl. Deshalb versu'),
        ('17:05', 'Dragon Ball Super', 'Eine rätselhafte Schönheit erscheint! Tenshinhans mysteriöses Dojo!', 'Anime', 30, 12, 'a10', 55, 'Son Gokus Truppe ist fast komplett. Es fehlen nur noch Muten-Roshi und Tenshinhan, damit Team Erde k'),
        ('17:35', 'Detektiv Conan', 'Der Pechvogel-Grandprix', 'Anime', 25, 12, 'a10', 55, 'Kogoro und Conan sind gerade auf der Suche nach einem Restaurant, als zwei Passanten von einem Auto '),
        ('18:00', 'One Piece', 'Die heilende Prinzessin - Rettet Mansherry!', 'Anime', 25, 12, 'a10', 55, 'Viola und die Zwerge dringen ins Schloss ein, um Prinzessin Mansherry zu befreien. Diese wird von Jo'),
        ('18:25', 'One Piece', 'Ein Duell zwischen Männern! - Senior Pink und das Klagelied der Liebe', 'Anime', 30, 12, 'a10', 55, 'In der Fabrik tragen Franky und Señor Pink noch immer ihren Kampf aus. Da beide großen Respekt fürei'),
        ('18:55', 'Detektiv Conan', 'Der Biss der Seeschlange - Teil 2', 'Anime', 25, 12, 'a10', 55, 'Kiwako liegt auf der Intensivstation. Die Suche nach der Krankenversicherung wird für die anderen zu'),
        ('20:15', 'Pompo: The Cinéphile', '', 'Serie', 105, 12, 'a10', 55, 'Der junge Gene arbeitet als persönlicher Assistent der erfolgreichen Filmproduzentin Joelle Davidovi'),
    ]),
    ("Freitag, 07.08.2026", "ZDFneo", [
        ('07:00', 'H2O - Plötzlich Meerjungfrau', 'Der Anhänger', 'Fantasyserie', 25, 10, 'a10', 55, 'Rikki entdeckt im Schaufenster eines Juweliers einen Anhänger, der dem von Cleo gleicht. Der Anhänge'),
        ('07:25', 'H2O - Plötzlich Meerjungfrau', "Lewis' Spezialdeo", 'Fantasyserie', 20, 10, 'a10', 55, 'Emma organisiert den Schulball. Während Zane Rikki brav fragt, ob sie mit ihm hingeht, warten Emma u'),
    ]),
    ("Freitag, 07.08.2026", "WDR", [
        ('07:25', 'Campsite', 'Theo ist verliebt', 'Jugendserie', 10, 3, 'a3', 55, 'Theo hat sich in Nura verliebt, aber was, wenn sie nicht dasselbe für ihn empfindet? Seine Freunde W'),
        ('07:35', 'Das Blubbern von Glück', '', 'Film', 95, 3, 'a3', 55, 'Als die zwölfjährige Candice sich in der Schule für ein Schulprojekt mit einer wahren Begebenheit ih'),
    ]),
    ("Freitag, 07.08.2026", "NDR", [
        ('06:00', 'Sesamstraße', '', 'Vorlesen', 20, 3, 'a3', 55, 'Jale (7) und Paula (7) bestaunen die Installation "The Wait" der skandinavischen Künstler Elmgreen &'),
        ('06:20', 'Schloss Einstein - Erfurt', 'Im Wrestling-Ring', 'Jugendserie', 25, 10, 'a10', 55, 'Bei Maxi und Karl wird es ernst, als die beiden den vermeintlichen Inhaber des zweiten Kartenstücks '),
        ('06:45', 'Schloss Einstein - Erfurt', 'Geheimnisse, Prioritäten und Pferdemist', 'Jugendserie', 25, 10, 'a10', 55, 'Für Leon bricht eine Welt zusammen, als er zufällig von Ios Vorhaben hinsichtlich ihrer schulischen '),
        ('07:10', 'Die Pfefferkörner', 'Die Öl-Mafia', 'Serie', 30, 10, 'a10', 55, 'Bei Djamila geht eine merkwürdige Lieferung ein: Bio-Olivenöl, das sie nie bestellt hat. Die Pfeffer'),
        ('07:40', 'Die Pfefferkörner', 'Spätfolgen', 'Serie', 35, 10, 'a10', 55, 'Hakim bekommt zufällig mit, wie der schmächtige Achtklässler Tjelle Gernhard auf der Schultoilette w'),
    ]),
    ("Freitag, 07.08.2026", "MDR", [
        ('18:54', 'Unser Sandmännchen', '', 'Serie', 6, 3, 'a3', 55, "Ein Eierbecher, der noch nie ein Ei gesehen hat? Gibt's denn so was? Ja, gibt es und genau hiervon h"),
    ]),
    ("Freitag, 07.08.2026", "RBB", [
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Liedergeschichten: Der Eierbecher'),
    ]),
    ("Freitag, 07.08.2026", "HR", [
        ('11:20', 'Neben der Spur ist auch ein Weg', '', 'Serie', 90, 6, 'a6', 55, 'Gibt es ein Leben nach der Trennung? Linda (Marlene Morreis) kann sich nur schwer vorstellen, ohne i'),
    ]),
    ("Freitag, 07.08.2026", "ORF 1", [
        ('06:00', 'ZIB KiDS', '', 'Serie', 10, 3, 'a3', 55, ''),
        ('06:10', 'Wickie und die starken Männer', 'Das Versprechen', 'Zeichentrick', 23, 3, 'a3', 55, 'Wickie gibt Ylvi das Versprechen, sie zu dem großen Fest im benachbarten Dorf zu begleiten. Die Wiki'),
        ('06:33', 'Servus Kasperl', 'Kasperl & Co: Spuk in der Kasperlvilla', 'Serie', 26, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:59', 'Die Jagd nach dem Kju Wang', 'Der Schatz des Herzogs', 'Zeichentrick', 23, 3, 'a3', 55, 'Venedig wird von einer großen Hitzewelle geplagt. Die Ernte ist bereits zerstört, das Wasser wird kn'),
        ('07:39', 'Galapagos X', 'Wer zuletzt lacht', 'Zeichentrick', 13, 3, 'a3', 55, 'In der Zukunft herrscht brütende Hitze und so muss die Crew von Galapagos X wieder einmal ausrücken,'),
        ('07:52', 'ZIB KiDS', '', 'Serie', 10, 3, 'a3', 55, ''),
    ]),
    ("Freitag, 07.08.2026", "SRF 1", [
        ('17:45', 'Pompon der kleine Bär', 'Lampefieber', 'Vorlesen', 15, 6, 'a6', 55, 'Pompon und Rita machen zum Abschied von Agnes, die in den Süden fliegt, ein Theaterstück und Pompon '),
    ]),
    ("Samstag, 08.08.2026", "ARD", [
        ('05:30', 'Arthur und die Freunde der Tafelrunde', 'Der Aufstand der Bauern', 'Zeichentrick', 10, 3, 'a3', 55, 'Die Bewohner von Camelot fragen sich, warum die Vorräte zur Neige gehen und plötzlich nicht mehr gen'),
        ('05:40', 'Arthur und die Freunde der Tafelrunde', 'Der Zauberkessel', 'Zeichentrick', 15, 3, 'a3', 55, 'Eine Hungersnot hat Camelot erfasst. Auch Merlin kann die Not nicht lindern. Sein Sättigungstrank is'),
        ('05:55', 'HobbyMania - Tausch mit mir dein Hobby!', 'Luftakrobatik vs. Segeln', 'Vorlesen', 25, 3, 'a3', 55, 'Im Segeln ist Eddy (12) ein echter Kracher. Dieses Jahr hat er es bis in den Deutschlandkader gescha'),
        ('07:05', 'Shaun das Schaf', 'Shiff ahoi!', 'Zeichentrick', 10, 3, 'a3', 55, 'Der Bauer schleppt ein altes Schiff auf den Hof. Hofhund Bitzer soll das gute Stück auf Vordermann b'),
        ('07:15', 'Anna im Land der tausend Seen', 'Ein neuer Räuber in der Wildnis', 'Vorlesen', 25, 3, 'a3', 55, 'Der Waschbär mag zwar niedlich aussehen, doch er hat es faustdick hinter den Ohren - das merkt Anna '),
        ('07:55', 'Checker Tobi', 'Der Leichtathletik-Check', 'Wissen', 25, 3, 'a3', 55, 'Checker Tobi lernt die verschiedensten Disziplinen der Leichtathletik kennen. Er trifft Jasmin, eine'),
        ('08:20', 'Wissen macht Ah! - Beweg dein Ah!', 'Beweg dein ah!', 'Vorlesen', 25, 6, 'a6', 55, 'Heute wird es sportlich im Ah!-Studio! Also raus aus dem Fernsehsessel und mitgemacht, während die b'),
        ('08:45', 'POV - Deine Geschichte zählt', 'Jung, mutig, sozial - Wenn Schüler Start-ups gründen', 'Vorlesen', 10, 6, 'a6', 55, 'Vlera (19) trägt früh Verantwortung: übersetzen, Behörden, Familie. Heute entwickelt sie mit ihrem T'),
        ('08:55', 'Die Pfefferkörner', 'Ein neues Hauptquartier', 'Serie', 25, 10, 'a10', 55, 'Lou und Pippa sind auf der Suche nach einem neuen Hauptquartier. Der Speicherboden von Pippas Mitsch'),
        ('09:20', 'Die Pfefferkörner', 'Bienenmord', 'Serie', 30, 10, 'a10', 55, 'Pippa engagiert sich in der Bienen-AG der Schule - und ist entsetzt, als nach einem brutalen Brandan'),
    ]),
    ("Samstag, 08.08.2026", "ZDF", [
        ('06:20', 'Dylans Spielkiste', 'Florist', 'Zeichentrick', 10, 3, 'a3', 55, 'Dylan schlüpft in die Rolle des Floristen. Für jeden seiner Freunde soll es einen passenden Blumenst'),
        ('06:30', 'Dylans Spielkiste', 'Bücherei', 'Zeichentrick', 10, 3, 'a3', 55, 'Dylan freut sich auf die Vorlesestunde, doch sein Buch fliegt auseinander. Die Seiten sind verwischt'),
        ('06:40', 'Meine Freundin Conni', 'Conni macht Musik', 'Zeichentrick', 10, 3, 'a3', 55, 'Conni leiht sich aus der Küche viele Küchengeräte für ihr erstes Hauskonzert. Von ihrem Topfdeckel-K'),
        ('06:50', 'Meine Freundin Conni', 'Conni am Strand', 'Zeichentrick', 10, 3, 'a3', 55, 'Sonne, Sommer, Strand und Meer. Urlaub ist einfach die schönste Jahreszeit, findet Conni. Es gibt so'),
        ('07:00', 'Die Biene Maja', 'Der meistgesuchte Mist', 'Zeichentrick', 15, 3, 'a3', 55, 'Mistkugeln sind die Lieblingsspielzeuge von Mistkäfern. Und Maja muss gleich zwei stinkende Mistkuge'),
        ('07:15', 'Die Biene Maja', 'Pauls Himbeere', 'Zeichentrick', 15, 3, 'a3', 55, 'Es ist mysteriös. Auf der Wiese verschwinden die Himbeeren der Ameisen. Schnell fällt der Verdacht a'),
        ('07:30', 'Bibi Blocksberg', 'Das siebte Hexbuch', 'Zeichentrick', 25, 3, 'a3', 55, 'Auf Burg Hexenstein findet ein internationales Hexentreffen statt. Bibi und ihre Freundin Schubia wä'),
        ('07:55', 'Bibi Blocksberg', 'Das chinesische Hexenkraut', 'Zeichentrick', 25, 3, 'a3', 55, 'Bibi und Schubia müssen nachsitzen und eine Heilsalbe nach einer alten chinesischen Rezeptur zuberei'),
        ('08:20', 'Robin Hood - Schlitzohr von Sherwood', 'Der verhexte Pokal', 'Zeichentrick', 15, 6, 'a6', 55, 'Zwei Nachbarn finden auf der Grenze ihrer Grundstücke einen Pokal. Obwohl sie vorher beste Freunde w'),
        ('08:35', 'Robin Hood - Schlitzohr von Sherwood', 'Marian verschwindet', 'Zeichentrick', 10, 6, 'a6', 55, 'Marian kommt ihr Zauberbuch abhanden. Es landet beim Buchhändler, der es an Prinz John verkauft. Der'),
        ('08:45', 'H2O - Abenteuer Meerjungfrau', 'Clownfisch vermisst', 'Zeichentrick', 25, 10, 'a10', 55, 'Die Clownfische Ziggy und Gus spielen im alten Wrack Verstecken. Dabei verschwindet Gus spurlos. Zig'),
        ('09:10', 'Bibi und Tina', 'Das Westernturnier', 'Zeichentrick', 25, 6, 'a6', 55, 'Das Ferienkind Tim trifft auf dem Martinshof ein. Der Junge will unbedingt das Falkensteiner Western'),
        ('09:35', 'Pippi Langstrumpf', 'Pippis Abschiedsfest', 'Serie', 25, 6, 'a6', 55, 'Seebär Efraim Langstrumpf ist nach langer Zeit heimgekehrt, um seine Tochter zu besuchen. Er möchte '),
        ('10:00', 'Pippi Langstrumpf', 'Pippi geht an Bord der Hoppetosse', 'Serie', 25, 6, 'a6', 55, 'Pippi Langstrumpfs Abreise steht unmittelbar bevor. Nicht einmal Pippis Grimassen können Tommy und A'),
    ]),
    ("Samstag, 08.08.2026", "SAT.1", [
        ('20:15', 'Hotel Transsilvanien 4: Eine Monster Verwandlung', '', 'Zeichentrick', 105, 10, 'a10', 55, 'Die Monster aus dem Hotel Transsilvanien bekommen es mit einer defekten Erfindung zu tun, die sie ku'),
    ]),
    ("Samstag, 08.08.2026", "ProSieben Maxx", [
        ('04:20', 'Frieren - Nach dem Ende der Reise', 'Das Ende der Reise', 'Anime', 25, 12, 'a10', 55, 'Frieren und ihre Begleiter haben den Dämonenkönig besiegt und kehren nach zehn Jahren nach Hause zur'),
        ('04:45', 'One Piece', 'Vorwärts Law! - Der letzte Kampf eines fürsorglichen Mannes', 'Anime', 25, 12, 'a10', 55, 'Corazon und De Flamingo waren zwar Brüder, doch im Herzen grundverschieden. Ihre gegensätzlichen Cha'),
        ('05:10', 'One Piece', 'Für die Freiheit! - Laws Injection Shot trifft ins Schwarze', 'Anime', 25, 12, 'a10', 55, 'Für Law gibt es kein Entkommen mehr: De Flamingo will seine Teufelskräfte. Ein Kampf um Leben und To'),
        ('05:55', 'Eyeshield 21', 'Wille zum Sieg', 'Anime', 25, 12, 'a10', 55, 'Die Devil Bats befinden sich noch immer im Spiel gegen die Kyoshin Poseidons. Beide Mannschaften geb'),
        ('06:20', 'Eyeshield 21', 'Der schauderhafte Mobby Dick Anchor', 'Anime', 25, 12, 'a10', 55, 'Es bleiben nur noch sieben Minuten im Spiel gegen die Kyoshin Poseidons übrig. Die Gegner nutzen ein'),
        ('06:45', 'Eyeshield 21', 'Der Kampf um die 30 Zentimeter', 'Anime', 25, 12, 'a10', 55, 'Sena schafft es endlich, an Shun vorbeizukommen, doch kurz vor der Endzone wird er von Kengo zu Fall'),
        ('07:10', 'Eyeshield 21', 'Der Mann, der schneller lief als sein Schatten', 'Anime', 25, 12, 'a10', 55, 'Mamori und Sena treffen auf Riku, den sie noch aus der Grundschule kennen. Damals hat der Junge Sena'),
        ('07:35', 'Die neuen Abenteuer des He-Man', 'Eine Bombe im Observatorium', 'Zeichentrick', 25, 3, 'a3', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:00', 'Die neuen Abenteuer des He-Man', 'Böse Träume', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:25', 'Die neuen Abenteuer des He-Man', 'Der Intelligenzverstärker', 'Zeichentrick', 30, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:55', 'She-Ra', 'Der widerspenstige Zauberer', 'Zeichentrick', 20, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('09:15', 'She-Ra', 'Echte Freunde', 'Zeichentrick', 25, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('09:40', 'Voltron: Legendärer Verteidiger', 'Schatten', 'Zeichentrick', 25, 6, 'a6', 55, 'Nach der Rettung der Erde stehen die Paladine vor einer neuen Bedrohung: Honerva setzt ihren bislang'),
        ('10:05', 'Voltron: Legendärer Verteidiger', 'Das Gefangenendilemma', 'Zeichentrick', 20, 6, 'a6', 55, 'Nachdem es den Paladinen gelungen ist, die Kontrolle über einen militärischen Galra-Stützpunkt zu üb'),
        ('10:25', 'She-Ra und die Rebellen-Prinzessinnen', 'Versprechen', 'Zeichentrick', 25, 6, 'a6', 55, 'Die Kriegerin She-Ra will ihren Planeten aus den Fängen der Horde befreien.'),
        ('10:50', 'Die neuen Abenteuer des He-Man', 'Mutantenhochzeit', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('11:15', 'Die neuen Abenteuer des He-Man', 'Pflanzenkrieg', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('11:40', 'Die neuen Abenteuer des He-Man', 'Gepples Sprengstoff', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('12:05', 'She-Ra', 'Nichts als Ärger', 'Zeichentrick', 25, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('12:30', 'She-Ra', 'Der König der Trolle', 'Zeichentrick', 20, 6, 'a6', 55, 'She-Ra kämpft gegen den finsteren Hordak und die Böse Horde.'),
        ('12:50', 'Voltron: Legendärer Verteidiger', 'Kampfwunden', 'Zeichentrick', 25, 6, 'a6', 55, 'Um Honervas durchtriebene Pläne aufzudecken, treiben die Paladine durch das Universum und beschließe'),
        ('13:15', 'Voltron: Legendärer Verteidiger', 'Der Groll', 'Zeichentrick', 30, 6, 'a6', 55, 'Das Ziel der Paladine, sich wieder mit der Atlas zu vereinen, wird jäh unterbrochen, als die Löwen v'),
        ('13:45', 'She-Ra und die Rebellen-Prinzessinnen', 'Light Hope', 'Zeichentrick', 20, 6, 'a6', 55, 'Die Kriegerin She-Ra will ihren Planeten aus den Fängen der Horde befreien.'),
        ('23:55', 'Dragon Ball Super', 'Die Universen stellen sich auf! Ein Konflikt der Absichten!', 'Anime', 25, 12, 'a10', 55, 'Während sich die Teilnehmer der Universen intensiv auf das Kampfturnier vorbereiten, hat Son Goku au'),
    ]),
    ("Samstag, 08.08.2026", "WDR", [
        ('08:10', 'Die Sendung mit dem Elefanten', 'Was macht man beim Judo?', 'Serie', 25, 3, 'a3', 55, 'In den Lach- und Sachgeschichten wird es heute bunt! Anke Engelke und Denis Moschitto stellen die "m'),
        ('08:35', 'Die Sendung mit der Maus', '', 'Vorlesen', 25, 6, 'a6', 55, 'Lach- und Sachgeschichten'),
        ('17:00', 'Garten & Lecker', 'Alte Schätze - neuer Garten in Lohmar', 'Serie', 45, 6, 'a6', 55, 'Finale - das letzte Gartenfest findet auf einer "Dorfwiese" in Lohmar statt. Diesen 10.000 Quadratme'),
        ('18:15', 'Lecker an Bord', 'Torfwurst und Hummelhûs', 'Serie', 30, 6, 'a6', 55, 'Mit ihrem Hausboot starten sie in Lemmer am Ijsselmeer und schippern über Seen und Kanäle ins Zentru'),
    ]),
    ("Samstag, 08.08.2026", "NDR", [
        ('07:00', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 3, 'a3', 55, '* Brennnesselstaub - Was kommt denn da für Staub aus den Brennnesseln? Das fragt sich Anna-Lena bei '),
    ]),
    ("Samstag, 08.08.2026", "MDR", [
        ('07:00', 'Meister Eder und sein Pumuckl', 'Der große Krach', 'Serie', 25, 3, 'a3', 55, 'Frau Gruber kommt mit ihrer Tochter Erika zu Meister Eder, um sich von ihm einen kleinen Schreibtisc'),
        ('07:25', 'Meister Eder und sein Pumuckl', 'Der große Krach und seine Folgen', 'Serie', 25, 3, 'a3', 55, 'Nach dem großen Krach sind Pumuckl und Meister Eder auseinandergegangen. Doch jeder vermisst den and'),
        ('18:54', 'Unser Sandmännchen', '', 'Serie', 6, 3, 'a3', 55, 'Moppi hat eine neue Gartenbank neben seiner Hütte. Er hat Pitti und Schnatterinchen eingeladen, die '),
    ]),
    ("Samstag, 08.08.2026", "RBB", [
        ('05:45', 'Schloss Einstein - Erfurt', '', 'Jugendserie', 25, 10, 'a10', 55, 'Tamas ist stocksauer. Clara hat ihm eine schwerwiegende Krankheit vorgespielt, um ihn zum Trompete-S'),
        ('06:10', 'Schloss Einstein - Erfurt', '', 'Jugendserie', 25, 10, 'a10', 55, 'Constanze kann es nicht länger ertragen, dass sie sich mit Elias den Chefredakteursposten teilen mus'),
        ('06:35', 'Schau in meine Welt', 'Lina, die Boxerin aus der Wüste', 'Vorlesen', 25, 3, 'a3', 55, 'Seitdem sie boxt, hat Lina das Gefühl, alle ihre Ziele erreichen zu können, wenn sie entschlossen is'),
        ('10:30', 'Rumpelstilzchen oder Das Zaubermännchen', '', 'Serie', 70, 6, 'a6', 55, 'Müller Kunz ist ein Prahlhans. Er behauptet, seine Tochter könne Stroh zu Gold spinnen. Der junge Kö'),
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Pittiplatsch: Als Moppi seine Gartenbank einweihen wollte'),
    ]),
    ("Samstag, 08.08.2026", "HR", [
        ('08:45', 'Schau in meine Welt', 'Linus, der Wasserspringer - auf dem Weg zur Meisterschaft', 'Vorlesen', 25, 6, 'a6', 55, 'Linus liebt es, vom Turm zu springen, durch die Luft zu fliegen und ins Wasser einzutauchen. Das mac'),
    ]),
    ("Samstag, 08.08.2026", "ORF 1", [
        ('06:00', 'Tom - Ein echter Freund', 'Tom in Kenia', 'Zeichentrick', 25, 3, 'a3', 55, 'Auf dem Weg nach Nairobi sind Tom, Tip und Wanda zunächst von stürmischer See, dann von Miss Hatch a'),
        ('06:25', 'Grizzy und die Lemminge', 'Lernen leicht gemacht!', 'Zeichentrick', 5, 3, 'a3', 55, 'In der Hütte des Rangers findet Grizzy einen "Lernhelm", mit dem man sich in Sekundenschnelle Fähigk'),
        ('06:30', 'Servus Kasperl', 'Kasperl & Pezi: Pezi & Kaspunzel', 'Serie', 25, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:55', 'Grizzy und die Lemminge', 'Wie alles begann…', 'Zeichentrick', 5, 3, 'a3', 55, 'Grizzy und die Lemminge erinnern sich, wie sie einander das erste Mal begegneten und gemeinsam die A'),
        ('07:00', 'Dora 3D', 'Zu viele Swipers / Batteos Baseball-Spiel', 'Zeichentrick', 25, 3, 'a3', 55, 'Zu viele Swipers: Tico hat eine neue Erfindung, diese macht aus einem Gegenstand vier. Aber das Gerä'),
        ('07:25', 'Helmi-Kinder-Verkehrs-Club', 'Wie der Blitz', 'Wissen', 5, 3, 'a3', 55, 'Sokrates hat Panik vor Gewittern. Kaum kündigt die Wetterprognose Gewitter an, verkriecht er sich. J'),
        ('07:30', 'ABC Bär', '', 'Vorlesen', 15, 3, 'a3', 55, 'Der ABC Bär und seine Tierfreunde reisen mit ihrem lustigen Baumhaus durch das Land, um ihre Zahl- u'),
        ('07:45', 'Kung Fu Panda: Die Tatzen des Schicksals', 'Geheime Wege', 'Zeichentrick', 25, 3, 'a3', 55, 'Obwohl die Dorfbewohner den jungen Kriegern in Ausbildung zur Seite stehen, hat Jindiao sie schnell '),
        ('08:10', 'Box', 'Socken', 'Wissen', 5, 6, 'a6', 55, 'Wer kennt das nicht? Nach dem Waschen ist oft nur noch ein Socken da… und was jetzt? Keine Sorge - w'),
        ('08:15', 'Tom Turbo', 'Spuknacht im Museum', 'Serie', 25, 6, 'a6', 55, 'Thomas Brezina erinnert sich an spannende Kriminalfälle, die er gemeinsam mit Tom Turbo im Detektivb'),
        ('08:55', 'Cyber Kids', 'Cookies', 'Wissen', 15, 6, 'a6', 55, 'Isabel und Valentin tüfteln gerade an ihrem Referat, als plötzlich eine Frage auftaucht: Was sind ei'),
        ('09:10', 'Der gestiefelte Kater - Abenteuer in San Lorenzo', 'Die silberne Kugel', 'Serie', 20, 6, 'a6', 55, 'Mit Hut und Degen zieht der gestiefelte Kater durchs Land, immer auf der Suche nach einem neuen Aben'),
        ('09:30', 'Tanzen mit den Stars', 'Salsa mit Vesela Dimova', 'Vorlesen', 15, 6, 'a6', 55, 'Heute bringt Vesela Dimova bei Tanzen mit den Stars unseren Tanzkinds die Grundlagen der Salsa bei. '),
        ('09:45', 'Klimakrach', 'Gemüse', 'Wissen', 15, 6, 'a6', 55, 'Waldemar ist besorgt, denn seine Tomatenpflanze ist kaputt. Er stellt sich die Frage, ob bei uns übe'),
        ('10:00', 'Dragons - Die Wächter von Berk', 'Der Skrill (2)', 'Zeichentrick', 20, 6, 'a6', 55, 'Der fiese Alvin und seine Männer haben den Skrill gefangen und ein Bündnis mit den Berserkern gesmsc'),
        ('10:20', '1000 Tricks', '', 'Vorlesen', 15, 6, 'a6', 55, 'Die Party kann beginnen! Melly und Christoph müssen nur noch das Geburtstagsgeschenk verpacken. Mit '),
        ('10:35', 'Ganz Ohr', 'Kacke', 'Vorlesen', 25, 6, 'a6', 55, 'Was passiert eigentlich mit unserem Kot - oder unserer "Kacke", wie wir im Alltag eher sagen - nachd'),
    ]),
    ("Sonntag, 09.08.2026", "ARD", [
        ('05:30', 'HipHorses - Du und Dein Pferd', 'Jonas und Westernpferd Wantani', 'Vorlesen', 25, 3, 'a3', 55, 'In Bösenburg hinter Halle lebt ein echter Cowboy. Jonas heißt er, ist zehn Jahre alt und sitzt oft i'),
        ('06:10', 'Tigerenten Club', 'Der Club zum Mitmachen - Spiele, Spaß und spannendes Wissen', 'Vorlesen', 60, 3, 'a3', 55, 'Rettungshunde im Einsatz Nase hoch, Rettung naht! Tamara Reiher ist mit Rettungshündin Beliz zu Gast'),
        ('09:30', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 6, 'a6', 55, 'Lach- und Sachgeschichten, heute mit Clarissa und einem Haufen Haaren, Trudes Tier und dem Traum vom'),
    ]),
    ("Sonntag, 09.08.2026", "ZDF", [
        ('06:00', 'Die Werkel-Ferkel', 'Trommel-Krach', 'Zeichentrick', 10, 3, 'a3', 55, 'Die Werkel-Ferkel freuen sich, denn heute ist Trommel-Krach-Tag. Doch die Freude wird getrübt, als p'),
        ('06:10', 'Die Werkel-Ferkel', 'Kleine "Melody"', 'Zeichentrick', 15, 3, 'a3', 55, 'Bernhard, der Bär, ist traurig. Er hat eine wunderschöne Blume, die nicht wachsen will. Und obwohl d'),
        ('06:25', 'Sam & Julia im Mäusehaus', 'Das große Klettern', 'Zeichentrick', 5, 3, 'a3', 55, 'Sam und Julia spielen im Treppenhaus Bergsteigen, als Ella zu ihnen stößt und sofort die Leitung des'),
        ('06:30', 'Sam & Julia im Mäusehaus', 'Der Nachwuchsmatrose', 'Zeichentrick', 10, 3, 'a3', 55, 'Opa Seemann erzählt Sam und Julia, wie er als kleiner Junge seinem Großvater immer beim Aufräumen un'),
        ('06:40', 'Sam & Julia im Mäusehaus', 'Das Mobile', 'Zeichentrick', 5, 3, 'a3', 55, 'Sams kleine Geschwister schlafen immer nur schwer ein. Oma Gouda erinnert sich, dass auch Sams Vater'),
        ('06:45', 'Pettersson und Findus', 'Eine Geburtstagstorte für die Katze', 'Zeichentrick', 15, 3, 'a3', 55, 'Findus ist schon in aller Frühe wach. Schließlich hat er Geburtstag. Unsanft reißt er den müden Pett'),
        ('07:00', 'Wickie und die starken Männer', 'Der Krake', 'Zeichentrick', 10, 3, 'a3', 55, 'Halvars Begehrlichkeit nach schönen Perlen ist geweckt. Doch die gibt es nur in einer Gegend, in der'),
        ('07:10', 'Wickie und die starken Männer', 'Auf den Kopf gestellt', 'Zeichentrick', 15, 3, 'a3', 55, 'Halvar und Sven sind sich nicht grün und donnern krachend mit den Köpfen gegeneinander. Danach ist n'),
        ('07:25', 'Bibi Blocksberg', 'Bibi und die Vampire', 'Zeichentrick', 25, 3, 'a3', 55, 'Hexentante Amanda schenkt den Blocksbergs einen Gutschein für eine Überraschungsreise. Erwartungsfro'),
        ('07:50', 'Bibi und Tina', 'Ein unfaires Rennen', 'Zeichentrick', 25, 3, 'a3', 55, 'Die Lindenhofbäuerin musste ihren Rappen Blacky verkaufen. Der neue Eigentümer, Friedhelm von Strauc'),
        ('08:15', 'Löwenzahn', 'Glas - Die Spur der blauen Scherbe', 'Serie', 25, 6, 'a6', 55, 'Fritz soll ein teures Glas-Kunstwerk seiner Schwester aufbewahren. Doch es kommt, wie es kommen muss'),
        ('08:40', 'Michel aus Lönneberga', 'Als Michel nur noch gute Vorsätze hatte', 'Serie', 23, 6, 'a6', 55, 'Michel und Knecht Alfred sind oft und gern in der freien Natur unterwegs. Eines Tages fragt Michel A'),
    ]),
    ("Sonntag, 09.08.2026", "SAT.1", [
        ('17:20', 'Hotel Transsilvanien 4: Eine Monster Verwandlung', '', 'Zeichentrick', 95, 6, 'a6', 55, 'Die Monster aus dem Hotel Transsilvanien bekommen es mit einer defekten Erfindung zu tun, die sie ku'),
    ]),
    ("Sonntag, 09.08.2026", "ProSieben Maxx", [
        ('04:05', 'One Piece', 'Die heilende Prinzessin - Rettet Mansherry!', 'Anime', 25, 12, 'a10', 55, 'Viola und die Zwerge dringen ins Schloss ein, um Prinzessin Mansherry zu befreien. Diese wird von Jo'),
        ('04:30', 'One Piece', 'Ein Duell zwischen Männern! - Senior Pink und das Klagelied der Liebe', 'Anime', 25, 12, 'a10', 55, 'In der Fabrik tragen Franky und Señor Pink noch immer ihren Kampf aus. Da beide großen Respekt fürei'),
        ('04:55', 'Detektiv Conan', 'Mord à la Carte (2)', 'Anime', 20, 12, 'a10', 55, 'Anscheinend hatten alle Kursteilnehmer ein Motiv für den Angriff und Mord an Frau Uemori. Conan mach'),
        ('05:15', 'Detektiv Conan', 'Nächtlicher Spuk in der Schule', 'Anime', 25, 12, 'a10', 55, 'Mitsuhiko und Genta erzählen Conan während der Unterrichtszeit, dass es in der Schule spuken soll. C'),
        ('05:40', 'Detektiv Conan', 'Die Strömung bringt es an den Tag', 'Anime', 25, 12, 'a10', 55, 'Kogoro, Ran und Conan verfahren sich und landen in einer schönen kleinen Stadt mit Strand und Meer. '),
    ]),
    ("Sonntag, 09.08.2026", "NDR", [
        ('06:45', 'Edgar, das Super-Karibu', 'Bosses Geburtstag', 'Zeichentrick', 10, 3, 'a3', 55, 'Es ist der Geburtstag von Bosse, dem missmutigen Igel. Super-Edgar würde ihm so gerne ein Geschenk m'),
        ('06:55', 'Edgar, das Super-Karibu', 'Bernhard, das Supereichhörnchen', 'Zeichentrick', 15, 3, 'a3', 55, 'Bernhard, das ungeschickte Eichhörnchen, beschließt, ein Superheld zu werden. So wie Super-Edgar. Au'),
    ]),
    ("Sonntag, 09.08.2026", "BR", [
        ('09:00', 'Der gestiefelte Kater', '', 'Serie', 60, 6, 'a6', 55, 'Nach dem Tod seines Vaters erbt der Müllerssohn Hans den Kater Minkus. Darüber ist er so enttäuscht,'),
        ('11:10', 'Ostwind - Zusammen sind wir frei', 'Zusammen sind wir frei', 'Film', 95, 6, 'a6', 55, 'Mika wird von ihren Eltern dazu gezwungen, ihre Sommerferien auf dem Gestüt ihrer strengen Großmutte'),
    ]),
    ("Sonntag, 09.08.2026", "MDR", [
        ('15:30', 'Die Gänseprinzessin', '', 'Serie', 60, 6, 'a6', 55, 'Die humorvolle und fröhliche Prinzessin Polly hat es nicht leicht. Das Königreich ihrer Eltern befin'),
        ('16:35', 'Der süße Brei', '', 'Serie', 85, 6, 'a6', 55, 'Eine große Hungersnot bedroht das Land. Schuld daran ist auch der gefürchtete Graf Ruben. Bevor die '),
        ('18:52', 'Unser Sandmännchen', '', 'Serie', 8, 3, 'a3', 55, 'Frau Elster saß zu lange in der Sonne und wird auch noch böse, als ihr Herr Fuchs nachweist, dass si'),
    ]),
    ("Sonntag, 09.08.2026", "RBB", [
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Kallis Gute-Nacht-Geschichten: Kalli - Biene'),
    ]),
    ("Sonntag, 09.08.2026", "ORF 1", [
        ('06:00', 'Tom - Ein echter Freund', 'Tom in Barcelona', 'Zeichentrick', 25, 3, 'a3', 55, 'Tom, Wanda und Tip lernen in Barcelona den auf Inlineskates rasenden Tortilla-Zusteller Jordi kennen'),
        ('06:25', 'Vegesaurier', 'Löcher graben', 'Zeichentrick', 5, 3, 'a3', 55, 'Ein Manderinterix weckt Ginger und die Erbs-Rex-Babys, weil er neben ihnen ein Loch nach dem anderen'),
        ('06:30', 'Servus Kasperl', 'Kasperl & Strolchi: Der Zauberturban', 'Serie', 25, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:55', 'Vegesaurier', 'Wenn die Kokosnüsse rollen', 'Zeichentrick', 5, 3, 'a3', 55, 'Zum Sommeranfang bestreiten Kokosnussodons und Annanasaurier gemeinsam ein außergewöhnliches Ritual.'),
        ('07:00', 'Vegesaurier', 'Die Popcornprüfung', 'Zeichentrick', 5, 3, 'a3', 55, 'Die jungen Kornosaurolofus-Saurier haben ein Ritual: Sie lassen ihre Maiskörner am heißen Vulkan zu '),
        ('07:05', 'Bakabu', 'Warum ist das so', 'Vorlesen', 5, 3, 'a3', 55, 'Bakabu und Mimi Lou haben ganz viele Fragen: Warum ist der Himmel blau? Warum ist das Eis so kalt? W'),
        ('07:10', 'Knall genial', '', 'Wissen', 15, 3, 'a3', 55, 'Originelle Tipps und Tricks von Thomas Brezina und den Kids! Was haben eine gruselige Burg, in der e'),
        ('07:25', 'Der gestiefelte Kater - Abenteuer in San Lorenzo', 'Der gestiefelte Pirat', 'Serie', 25, 3, 'a3', 55, 'Mit Hut und Degen zieht der gestiefelte Kater durchs Land, immer auf der Suche nach einem neuen Aben'),
        ('07:50', 'Drunter & drüber mit Christoph Hirschler', '"Stimmenmacher" mit Puppenspieler Raphael Kovarik', 'Vorlesen', 15, 3, 'a3', 55, 'Puppenspieler Raphael Kovarik kommt heute mit seiner selbstgebauten Krokodil-Puppe in Christophs Sho'),
        ('08:05', 'Campsite', 'Der beste Platz', 'Jugendserie', 10, 10, 'a10', 55, 'Silje möchte mit ihren Freundinnen einen entspannten Tag an ihrem Lieblingsplatz verbringen, aber im'),
        ('08:15', 'Campsite', 'Endlich alleine', 'Jugendserie', 5, 10, 'a10', 55, 'Siljes große Schwester Emmi möchte etwas Zeit für sich alleine haben und deshalb alleine zelten gehe'),
        ('08:20', 'Campsite', 'Der Revolver ist weg', 'Jugendserie', 10, 10, 'a10', 55, 'Beim gemeinsamen Krimi-Brettspiel kommt ein kleiner Plastikrevolver abhanden. Sebbe beschuldigt Will'),
        ('08:30', 'Dragons - Die Wächter von Berk', 'Gustavs Feuerprobe', 'Zeichentrick', 20, 6, 'a6', 55, 'Rotzbakke hat die fünf Zeichen von Walhalla gesehen und glaubt nun, er müsse sterben. Den Tod vor Au'),
        ('08:50', 'Was geht?', 'Schlaf', 'Wissen', 15, 6, 'a6', 55, 'Wie viel Schlaf brauchen Kinder wirklich - und warum ist er so wichtig? Samira (10), Max (10) und Wo'),
        ('09:05', 'Mini Spezial', 'Esel', 'Vorlesen', 5, 6, 'a6', 55, 'Sind Esel wirklich so stur? Das will Julia heute herausfinden und besucht daher Michaela. Die besitz'),
        ('09:10', 'Garfield', 'Cousine Petunia', 'Zeichentrick', 15, 6, 'a6', 55, 'Bei Garfield zu Hause wird heute Besuch empfangen. Jons Nichten verbringen ein paar Tage bei ihnen. '),
        ('09:25', 'Hallo, was machst Du?', 'Alm', 'Wissen', 15, 6, 'a6', 55, 'Vier Monate jeden Tag arbeiten - aber dafür umgeben von wunderschöner Natur und lieben Kühen? Almhir'),
    ]),
]
