# -*- coding: utf-8 -*-
"""Kindersendungen der Vollprogramme.

Erzeugt von scan_kinder.py aus tv.de am 28.08.2026. Auswahl nach Kategorie,
bekannten Titeln und Beschreibung; Alterswerte heuristisch.
"""

TAGE = [
    ("Freitag, 28.08.2026", "ProSieben Maxx", [
        ('18:25', 'One Piece', 'Sakeschalen der Gefolgschaft - Die Entstehung der Strohhut-Großflotte!', 'Anime', 30, 12, 'a10', 55, 'Im Kampf gegen de Flamingo schließen sich Ruffys Anhänger zu einer mächtigen Truppe zusammen. Kann d'),
        ('18:55', 'Detektiv Conan', 'Den Männern in Schwarz auf der Spur (1)', 'Anime', 25, 12, 'a10', 55, 'In der Klasse 1B der Teitan Grundschule wird eine neue Schülerin erwartet: Ai Haibara. Die Lehrerin '),
        ('20:15', 'Naruto Shippuden the Movie', '', 'Zeichentrick', 105, 12, 'a10', 55, 'Als ein mächtiger Dämon ins Reich der Lebenden zurückkommt, beschließt Naruto, die Schamanin Shion z'),
        ('22:00', 'Gachiakuta', 'Das Hauptquartier des Putztrupps', 'Anime', 30, 12, 'a10', 55, 'Enjin und die anderen bringen Rudo in das Hauptquartier des Putztrupps. Dort angekommen, erhält er e'),
        ('22:30', 'Gachiakuta', 'Die Vandalen', 'Anime', 30, 12, 'a10', 55, 'Der Putztrupp veranstaltet eine Willkommensfeier für Rudo. Der Junge ist jedoch gar nicht in Partyst'),
        ('23:00', 'Gachiakuta', 'Die volle Breitseite!', 'Anime', 20, 12, 'a10', 55, 'Rudo und zwei seiner Kollegen vom Putztrupp treffen auf den Vandalen Jabber, der ihnen den Weg versp'),
        ('23:50', 'Frieren - Nach dem Ende der Reise', 'Der Held des Dorfes', 'Anime', 25, 12, 'a10', 55, 'Fern bittet Stark, ihr und Frieren beim Kampf gegen den Drachen zu helfen. Der Junge hat zwar Angst '),
    ]),
    ("Freitag, 28.08.2026", "WDR", [
        ('21:15', 'Wuppertal und die einzigartige Schwebebahn', '', 'Wissen', 30, 10, 'a10', 55, 'Einmal im Leben durch Wuppertal schweben! Die Wuppertaler Schwebebahn feiert ihren 125. Geburtstag -'),
    ]),
    ("Freitag, 28.08.2026", "MDR", [
        ('18:54', 'Unser Sandmännchen', '', 'Serie', 6, 3, 'a3', 55, 'In diesem traditionellen chinesischen Wiegenlied wird das Bett im Traum zu einem Schiff, mit dem das'),
    ]),
    ("Samstag, 29.08.2026", "ARD", [
        ('05:30', 'Arthur und die Freunde der Tafelrunde', 'Die Nadel der Gerechtigkeit', 'Zeichentrick', 10, 3, 'a3', 55, 'Arthur darf nicht am großen Ritterturnier teilnehmen, weil er nicht von edlem Blut ist. Morgan hat e'),
        ('05:40', 'Arthur und die Freunde der Tafelrunde', 'Die versprochene Braut', 'Zeichentrick', 15, 3, 'a3', 55, 'Guinevere ist in Not. Ihre Eltern wollen sie gegen ihren Willen verheiraten. Arthur und seine Freund'),
        ('05:55', 'HobbyMania - Tausch mit mir dein Hobby!', 'Skispringen vs. Chor', 'Vorlesen', 25, 3, 'a3', 55, 'Wenn Emily (10) auf ihren Skiern durch die Luft gleitet, fühlt sie sich frei wie ein Vogel. Auf der '),
        ('07:05', 'Shaun das Schaf', 'Sehr verdächtig', 'Zeichentrick', 10, 3, 'a3', 55, 'Der schrille Lärm von Bitzers Trillerpfeife macht den Hoftieren das Leben schwer. Am nächsten Morgen'),
        ('07:15', 'Anna im Land der tausend Seen', 'Der König des Waldes', 'Vorlesen', 25, 3, 'a3', 55, 'Wenn die Kraniche morgens erwachen, beginnt das Kranich-Konzert. Anna ist live dabei und beobachtet,'),
        ('07:40', 'Nina und die Haustiere', 'Ein Tag mit Herdenschutzhunden', 'Vorlesen', 15, 3, 'a3', 55, 'Nina ist in der Nähe von Hamburg unterwegs. Sie besucht eine Schäferin, die ihre Schafe mit Herdensc'),
        ('07:55', 'Checkerin Marina', 'Der Ruder-und-Paddel-Check', 'Wissen', 25, 3, 'a3', 55, 'Beim Paddeln am See trifft Marina eine Ruder-Mannschaft in einem Achter. Sie möchte unbedingt wissen'),
        ('08:20', 'Wissen macht Ah!', 'Urlaub im Urwald', 'Vorlesen', 25, 6, 'a6', 55, 'Clarissa und Ralph widmen die heutige Sendung einem ganz besonderen Naturforscher: Alexander von Hum'),
        ('08:45', 'POV - Deine Geschichte zählt', 'Was tun, wenn keiner was sagt - - Rechtsextremismus unter Jugendlichen', 'Vorlesen', 10, 6, 'a6', 55, 'Rechte Sprüche, Nazi-Memes und rassistische Witze gehörten für Curcuma zum Schulalltag. Heute stellt'),
        ('08:55', 'Die Pfefferkörner', 'Die tollste Tante der Welt', 'Serie', 25, 10, 'a10', 55, 'Lous Patentante Jenny, die auf einem Kreuzfahrtschiff als Hostess arbeitet, legt im Hamburger Hafen '),
        ('09:20', 'Die Pfefferkörner', 'Der Schutzengel', 'Serie', 30, 10, 'a10', 55, 'Pippa wird von ihrer Mitschülerin Edda und ihrem Mitschüler Benni auf dem Schulhof fies angegangen -'),
        ('14:00', 'Im Fluss des Lebens', '', 'Film', 90, 6, 'a6', 55, 'Die Berliner Schriftstellerin Agnes Berg (Ruth Maria Kubitschek) erhält einen Literaturpreis für ihr'),
    ]),
    ("Samstag, 29.08.2026", "ZDF", [
        ('06:20', 'Dylans Spielkiste', 'Astronaut auf neuer Mission', 'Zeichentrick', 10, 3, 'a3', 55, 'Dylan ist wieder Astronaut und muss den "Daisy-Saturn" retten, der seinen Ring verloren hat und auf '),
        ('06:30', 'Dylans Spielkiste', 'Modedesigner', 'Zeichentrick', 10, 3, 'a3', 55, 'Dylan will als Modedesigner ein einzigartiges Outfit kreieren. Doch die kritische Fotografin Daisy t'),
        ('06:40', 'Meine Freundin Conni', 'Conni geht zum Kinderarzt', 'Zeichentrick', 10, 3, 'a3', 55, 'Conni wundert sich. Warum muss sie zum Arzt, wenn sie doch ganz gesund ist? Mama erklärt ihr, dass s'),
        ('06:50', 'Meine Freundin Conni', 'Conni sucht Kater Mau', 'Zeichentrick', 10, 3, 'a3', 55, 'Conni liebt es, wenn ihr Kater nach seinen Streifzügen mit ihr kuschelt. Doch heute wartet sie verge'),
        ('07:00', 'Die Biene Maja', 'Walter hat den Durchblick', 'Zeichentrick', 15, 3, 'a3', 55, 'Normalerweise möchte Maja einem Vogelschnabel nicht zu nahe kommen. Und wenn, dann sollte der Schnab'),
        ('07:15', 'Die Biene Maja', 'Majas Schatz', 'Zeichentrick', 15, 3, 'a3', 55, 'Maja geht auf Schatzsuche - und zwar nach ihrem eigenen Schatz! Denn sie verliert ihre Schatzkarte, '),
        ('07:30', 'Bibi Blocksberg', 'Reise in die Vergangenheit', 'Zeichentrick', 25, 3, 'a3', 55, 'Weil ihre Frauen einen Hexenkongress besuchen, sind Bernhard Blocksberg und Patrick Thunderstorm für'),
        ('07:55', 'Bibi Blocksberg', 'Der zerbrochene Besen', 'Zeichentrick', 25, 3, 'a3', 55, 'Bibi ist verzweifelt. Ein Blitz ist in Kartoffelbrei eingeschlagen und hat ihn zerbrochen. Nun liegt'),
        ('08:20', 'Robin Hood - Schlitzohr von Sherwood', 'Peter, der Hartherzige', 'Zeichentrick', 15, 6, 'a6', 55, 'Robin und seine Freunde beobachten, wie Prinz John einen jungen Mann schindet. Sie wollen dem armen '),
        ('08:35', 'Robin Hood - Schlitzohr von Sherwood', 'Schule für Gentlemen', 'Zeichentrick', 10, 6, 'a6', 55, 'Robin bekommt einen Brief von seinem Vater, in dem dieser verlangt, dass Robin Unterricht bei Lady R'),
        ('08:45', 'H2O - Abenteuer Meerjungfrau', 'Valentinstag', 'Zeichentrick', 25, 10, 'a10', 55, 'Es ist Valentinstag, und Lewis möchte Cleo ins Kino einladen. Doch Cleo lehnt überrumpelt ab. Enttäu'),
        ('09:10', 'Bibi und Tina', 'Tina in Gefahr', 'Zeichentrick', 25, 6, 'a6', 55, 'Graf von Falkenstein hat die Handwerker im Haus. Die zwielichtigen Gesellen haben es auf die wertvol'),
        ('09:35', 'Pippi Langstrumpf', 'Pippi und die Seeräuber (3)', 'Serie', 25, 6, 'a6', 55, 'Die Nachricht von Pippis Ankunft auf Taka-Tuka-Land löst unter den Seeräubern Furcht und Schrecken a'),
        ('10:00', 'Pippi Langstrumpf', 'Pippi und die Seeräuber (4)', 'Serie', 25, 6, 'a6', 55, 'Efraim Langstrumpf wird in einem "einbruchsicheren" Verlies in der Festung auf der Pirateninsel gefa'),
    ]),
    ("Samstag, 29.08.2026", "SAT.1", [
        ('20:15', 'Matilda', '', 'Film', 125, 10, 'a10', 55, 'Kaum zu glauben, dass solche Eltern eine solche Tochter haben: Die kleine Matilda ist ein telekineti'),
    ]),
    ("Samstag, 29.08.2026", "ProSieben Maxx", [
        ('04:10', 'Frieren - Nach dem Ende der Reise', 'Wie aus einem Märchen', 'Anime', 20, 12, 'a10', 55, 'Frieren, Fern und Stark sind in den Nördlichen Ländern unterwegs und helfen dabei, eine versperrte S'),
        ('04:30', 'One Piece', 'Ein Notfall - Rebecca wird entführt!', 'Anime', 25, 12, 'a10', 55, 'Bei einem Angriff auf die Strohhüte gelingt es Ruffy, Rebecca zu entführen. Der Pirat hat den Plan, '),
        ('04:55', 'One Piece', 'Das Band zwischen Vater und Tochter - Kyros und Rebecca!', 'Anime', 25, 12, 'a10', 55, 'Rebecca steht nach ihrer abenteuerlichen Reise endlich ihrem Vater Kyros gegenüber und offenbart die'),
        ('05:20', 'One Piece', 'Der Stolz eines Mannes - Ruffys Kopf-an-Kopf-Kampf gegen Fujitora!', 'Anime', 20, 12, 'a10', 55, 'Während Sengoku ein ernstes Wörtchen mit Law wechselt, will Fujitora seinen teuflischen Pan in die T'),
        ('05:55', 'Eyeshield 21', 'Der Kick des Schicksals', 'Anime', 25, 12, 'a10', 55, 'Die letzte Minute im Spiel zwischen den Devil Bats und den Wild Gunmen läuft: Kid und Yoichi liefern'),
        ('06:20', 'Eyeshield 21', 'Ein Eid unter Rivalen', 'Anime', 25, 12, 'a10', 55, 'Die Devil Bats haben das Halbfinale gegen die Wild Gunmen verloren. Doch es gibt noch eine letzte Mö'),
        ('06:45', 'Eyeshield 21', 'Gefährliche Spiders', 'Anime', 25, 12, 'a10', 55, 'Im zweiten Halbfinale des Turniers treffen die Ojo White Knights auf die Bando Spiders. Sena und sei'),
        ('07:10', 'Eyeshield 21', 'Komm zurück! Musashi!', 'Anime', 25, 12, 'a10', 55, 'In ihrem nächsten Match müssen die Devil Bats gegen die Bando Spiders antreten. Um die starken Gegne'),
        ('07:35', 'Die neuen Abenteuer des He-Man', 'Die Legende von Zil', 'Zeichentrick', 25, 3, 'a3', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:00', 'Die neuen Abenteuer des He-Man', 'Der Ruf der Herde', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:25', 'Die neuen Abenteuer des He-Man', 'Das Innere des Vulkans', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('08:50', 'She-Ra', 'Der ehrgeizige Lehrling', 'Zeichentrick', 25, 6, 'a6', 55, 'Ariel, die ehrgeizige Schülerin der Zauberin Castaspella, ist in ihrem Übermut davon überzeugt, die '),
        ('09:15', 'She-Ra', 'Zoogeschichten', 'Zeichentrick', 20, 6, 'a6', 55, 'Hordak und seine Untertanen fangen alle Tiere des Waldes des Friedens ein und sperren sie in einen Z'),
        ('09:35', 'Voltron: Legendärer Verteidiger', 'Strahlentag', 'Zeichentrick', 25, 6, 'a6', 55, 'Die Atlas und die Löwen erreichen den Planeten Drazan, um an den Feierlichkeiten des Clear Day teilz'),
        ('10:00', 'Voltron: Legendärer Verteidiger', 'Ritter des Lichts (1)', 'Zeichentrick', 25, 6, 'a6', 55, 'Die Paladine sehen sich einer heiklen Aufgabe gegenüber: Angeführt von Allura dringen sie tief in Ho'),
        ('10:25', 'She-Ra und die Rebellen-Prinzessinnen', 'Der gefrorene Wald', 'Zeichentrick', 25, 6, 'a6', 55, 'Die Prinzessinnen-Allianz setzt alles daran, die Whispering Woods gegen die Angriffe der Horde zu ve'),
        ('10:50', 'Die neuen Abenteuer des He-Man', 'Hilferuf aus dem Weltall', 'Zeichentrick', 20, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('11:10', 'Die neuen Abenteuer des He-Man', 'Der elektrische He-Man', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('11:35', 'Die neuen Abenteuer des He-Man', 'Die Königin der Mytes', 'Zeichentrick', 25, 6, 'a6', 55, 'Prinz Adam muss auf dem Planeten Primus gegen gefährliche Mutanten kämpfen.'),
        ('12:00', 'She-Ra', 'Die Welt der Dunkelheit', 'Zeichentrick', 25, 6, 'a6', 55, 'Eine von Hordaks Waffen hat eine Fehlzündung, was dazu führt, dass er und She-Ra in einer anderen Di'),
        ('12:25', 'She-Ra', 'Der Schatz der Gründer', 'Zeichentrick', 20, 6, 'a6', 55, 'Hordak hat es auf einen Schatz abgesehen, der ein Geheimnis enthüllt, mit dem man die Rebellen endgü'),
        ('12:45', 'Voltron: Legendärer Verteidiger', 'Ritter des Lichts (2)', 'Zeichentrick', 25, 6, 'a6', 55, 'Während sie immer tiefer in Honervas Gedankenwelt eintauchen, sehen sich die Paladine sowohl alten a'),
        ('13:10', 'Voltron: Legendärer Verteidiger', 'Unbekannte Regionen', 'Zeichentrick', 30, 6, 'a6', 55, 'Während Honerva ihren Plan weiter vorantreibt, spaltet sich die Voltron-Koalition, um sie aufzuhalte'),
        ('13:40', 'She-Ra und die Rebellen-Prinzessinnen', 'Eine heilige Verbindung', 'Zeichentrick', 20, 6, 'a6', 55, 'Bow und Glimmer wollen herausfinden, was mit Entrapta passiert ist. Dabei nehmen sie aus Versehen Ca'),
    ]),
    ("Samstag, 29.08.2026", "WDR", [
        ('07:40', 'Die Sendung mit dem Elefanten', 'Wie können dicke Hummeln so gut fliegen?', 'Serie', 25, 3, 'a3', 55, 'In der "Sendung mit dem Elefanten" geht es heute um die zwei Brüder Ramon und Romeo, die in einer ge'),
        ('08:05', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 6, 'a6', 55, 'Lach- und Sachgeschichten'),
        ('08:35', 'Die Sendung mit der Maus Spezial', 'Leverkusener Brücke', 'Vorlesen', 70, 6, 'a6', 55, 'Wie wird eine Brücke gebaut? Armin hat mit dem Maus-Team über viele Jahre den Bau der neuen Leverkus'),
    ]),
    ("Samstag, 29.08.2026", "NDR", [
        ('07:00', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 3, 'a3', 55, 'Lach- und Sachgeschichten, heute mit einer Gottesanbeterin auf der Lauer, einem großen Monster im Wa'),
    ]),
    ("Samstag, 29.08.2026", "BR", [
        ('12:00', 'Dann kam Lucy', '', 'Serie', 90, 6, 'a6', 55, 'Zehn Jahre ist es her, seit die Pferdezüchterin Saskia ihre Jugendfreundin Andrea zuletzt gesehen ha'),
    ]),
    ("Samstag, 29.08.2026", "MDR", [
        ('06:45', 'Meister Eder und sein Pumuckl', 'Der verhängnisvolle Schlagrahm', 'Serie', 25, 3, 'a3', 55, 'Eder bekommt Besuch von seiner Cousine Irma und ihrem Sohn Fritz. Es gibt Kaffee, Kuchen und eine gr'),
        ('07:10', 'Meister Eder und sein Pumuckl', 'Pumuckl im Zoo', 'Serie', 25, 3, 'a3', 55, 'Meister Eder und Pumuckl gehen in den Zoo. Die vielen fremden Tiere sind neu und aufregend für den k'),
        ('18:54', 'Unser Sandmännchen', '', 'Serie', 6, 3, 'a3', 55, 'Herr Fuchs borgt sich den Sonnenschirm der Elster. Diese ist verwundert, denn der Sommer ist vorüber'),
    ]),
    ("Samstag, 29.08.2026", "RBB", [
        ('05:45', 'Schloss Einstein', '', 'Jugendserie', 25, 10, 'a10', 55, 'Nach einem gemeinsamen Kinobesuch mit Clara, Jo und Tamas verletzt Sándor Jo mit einer unüberlegten '),
        ('06:10', 'Schloss Einstein', '', 'Jugendserie', 25, 10, 'a10', 55, 'Pippi kann wegen eines umgeknickten Fußes nicht an der letzten Runde des Geocaching-Wettbewerbs teil'),
        ('06:35', 'Annika und Hanna - Feuerwehrfreundinnen', '', 'Vorlesen', 25, 3, 'a3', 55, 'Annika Franzen lebt in Eching am Ammersee. Die 13-Jährige hat sich schon immer für die Feuerwehr int'),
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Fuchs und Elster: Herr Fuchs borgt einen Sonnenschirm'),
    ]),
    ("Samstag, 29.08.2026", "HR", [
        ('04:00', 'Soul Shift', 'Revolutionär Evolutionär', 'Zeichentrick', 10, 3, 'a3', 55, 'Auf Tau-Blaus Erde haben sich verschiedenste Arten von Reptilien und Echsen entwickelt. Eisengrün tr'),
        ('04:10', 'Soul Shift', 'Glückwunsch! Es ist ein Asteroid', 'Zeichentrick', 10, 3, 'a3', 55, 'Auf der Erde hat es die Evolution bis zur Dinosaurier-Bevölkerung gebracht. In brutalen Auseinanders'),
        ('04:20', 'Soul Shift', 'Das Ende naht', 'Zeichentrick', 15, 3, 'a3', 55, 'Die Evolutionsmanager präsentieren dem Allmächtigen den Zwischenstand der Evolution auf ihrem jeweil'),
        ('04:35', 'Soul Shift', 'Degradiert und absorbiert', 'Zeichentrick', 10, 3, 'a3', 55, 'Tau-Blau verliert nach der Verwüstung auf der Erde seinen Job. Der Planet Conglom ist beim Asteroide'),
        ('04:45', 'Soul Shift', 'Planet der Primaten', 'Zeichentrick', 10, 3, 'a3', 55, 'Tau-Blau, inzwischen zur normalen Seele degradiert, begibt sich auf Inkarnationsreisen auf die Erde.'),
        ('04:55', 'Soul Shift', 'Die Schatten', 'Zeichentrick', 15, 3, 'a3', 55, 'Die Ereignisse überstürzen sich. Tau-Blau wird auf Befehl des Allmächtigen überwältigt und in die Sc'),
        ('05:10', 'Soul Shift', 'Die Show muss weitergehen', 'Zeichentrick', 10, 3, 'a3', 55, 'Tau-Blau absorbiert inzwischen alles Leben auf den verbliebenen Planeten. Sonnengelb, der Tau-Blau s'),
        ('08:50', 'Schau in meine Welt', 'Sammys erste Filmrolle', 'Vorlesen', 25, 6, 'a6', 55, 'Samanta Lillia (13) hat ihre erste Rolle beim Film. Als Sängerin stand sie schon auf vielen Bühnen. '),
    ]),
    ("Samstag, 29.08.2026", "arte", [
        ('04:25', 'Athleticus', 'Seilakrobatik', 'Zeichentrick', 50, 3, 'a3', 55, 'Ein Flamingo fährt Einrad auf einem Seil, das zwischen zwei Hochhäusern gespannt ist. Der Elefant so'),
    ]),
    ("Samstag, 29.08.2026", "ORF 1", [
        ('06:00', 'Tom - Ein echter Freund', 'Tom in Ägypten', 'Zeichentrick', 25, 3, 'a3', 55, 'Auch in Ägypten stoßen Tom und seine Freunde auf Carters Komplizen. Diesmal haben es Weedon und Miss'),
        ('06:25', 'Grizzy und die Lemminge', 'Die Schmetterlingsjäger', 'Zeichentrick', 5, 3, 'a3', 55, 'Grizzys Angebetete ist von Schmetterlingen ziemlich angetan. Deshalb will er ihr einen Schmetterling'),
        ('06:30', 'Servus Kasperl', 'Kasperl & Leopold: Die Wunschkette', 'Serie', 25, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:55', 'Grizzy und die Lemminge', 'Brandneue Turnschuhe!', 'Zeichentrick', 5, 3, 'a3', 55, 'In der Hütte des Rangers finden die Lemminge ein Paar nagelneue Turnschuhe und haben auch sogleich i'),
        ('07:00', 'Dora 3D', 'Der Zungenknoten / Mampfi und die Wolkenblume', 'Zeichentrick', 25, 3, 'a3', 55, 'Der Zungenknoten: Durch das Aufsagen eines Zungenbrechers hat der grummelige alte Troll einen Knoten'),
        ('07:25', 'Helmi-Kinder-Verkehrs-Club', 'Voll da am Schulweg', 'Wissen', 5, 3, 'a3', 55, 'Sokrates ist ununterbrochen am Laptop und hängt deshalb irrtümlich sein Ohr ins Kakaohäferl, weil er'),
        ('07:30', 'ABC Bär', '', 'Vorlesen', 15, 3, 'a3', 55, 'Der ABC Bär und seine Tierfreunde reisen mit ihrem lustigen Baumhaus durch das Land, um ihre Zahl- u'),
        ('07:45', 'Kung Fu Panda: Die Tatzen des Schicksals', 'Die Quelle wird geöffnet', 'Zeichentrick', 25, 3, 'a3', 55, 'Jindiao hat Po und seine Schüler gefunden und ist seinem finsteren Ziel einen Schritt näher gekommen'),
        ('08:10', 'Box', 'Basteln', 'Wissen', 5, 6, 'a6', 55, 'Ein federleichter Schlüsselanhänger, aromatisch duftende Blütenkerzen und ein fuchstastischer Tassen'),
        ('08:15', 'Tom Turbo', 'Der Hund aus dem All', 'Serie', 25, 6, 'a6', 55, 'Thomas Brezina erinnert sich an spannende Kriminalfälle, die er gemeinsam mit Tom Turbo im Detektivb'),
        ('08:55', 'Cyber Kids', 'Virus', 'Wissen', 15, 6, 'a6', 55, 'Wie gefährlich sind Computerviren? Valentin bekommt eine E-Mail, die zu schön klingt, um wahr zu sei'),
        ('09:10', 'Der gestiefelte Kater - Abenteuer in San Lorenzo', 'Das Geheimnis der Schwestern', 'Serie', 20, 6, 'a6', 55, 'Mit Hut und Degen zieht der gestiefelte Kater durchs Land, immer auf der Suche nach einem neuen Aben'),
        ('09:30', 'Tanzen mit den Stars', 'Rumba mit Katrin Kallus', 'Vorlesen', 15, 6, 'a6', 55, 'Heute bei Tanzen mit den Stars zeigt Dancing Stars Profi Kati Kallus unseren Tanzkinds die Rumba-Gru'),
        ('09:45', 'Klimakrach', 'Krach fürs Klima', 'Wissen', 15, 6, 'a6', 55, 'Waldemar ist traurig, weil er sich mehr für den Klimaschutz starkmachen möchte, aber nicht weiß, was'),
        ('10:00', 'Dragons - Die Wächter von Berk', 'Drachentausch', 'Zeichentrick', 20, 6, 'a6', 55, 'Dass sich Rotzbakke und Astrid nicht leiden können, weiß jeder auf Berk. Als aus heiterem Himmel abe'),
        ('10:20', '1000 Tricks', '', 'Vorlesen', 15, 6, 'a6', 55, 'Die Magierinnen und Magier Melly, Christoph, Magic Max und Tristan zeigen wie sie Paprika und Saftpa'),
        ('10:35', 'Ganz Ohr', 'Klimaangst', 'Vorlesen', 21, 6, 'a6', 55, 'Viele Kinder und Jugendliche haben Angst vor der Zukunft. Sie fürchten sich vor den Folgen des Klima'),
        ('10:56', 'Galapagos X', 'Schädlingsbefall', 'Zeichentrick', 9, 6, 'a6', 55, 'Raes kleiner Bruder Shade ist zu Besuch. Als er hört, wie die anderen über Insekten denken, kapert e'),
    ]),
    ("Samstag, 29.08.2026", "SRF 1", [
        ('10:55', 'SRF Kids News', '', 'Serie', 15, 6, 'a6', 55, ''),
        ('11:10', 'SRF Kids Inside', 'IG Seifenkisten Derby Schweiz - Schnelligkeit ohne Motor', 'Vorlesen', 15, 6, 'a6', 55, '1 Verein, 3 Kids und noch mehr Storys: «SRF Kids Inside» erzählt Geschichten mitten aus dem Leben.'),
        ('11:25', 'SRF Kids News spezial', 'Was ist Mobbing? Und was kannst du dagegen tun?', 'Vorlesen', 20, 6, 'a6', 55, 'Wie die wöchentlichen «SRF Kids News» zeigen die «SRF Kids News spezial» ausgewählte Themen, aber mi'),
        ('17:40', 'Minisguard', 'Wie macht man eigentlich Glace?', 'Serie', 20, 6, 'a6', 55, 'An einem heissen Sommertag gibt es kaum etwas Besseres als eine feine Glace. Aber wie wird Glace eig'),
    ]),
    ("Sonntag, 30.08.2026", "ARD", [
        ('05:30', 'HipHorses - Du und Dein Pferd', 'Annika und Spring-Pony Oh-Fiona', 'Vorlesen', 25, 3, 'a3', 55, 'Annika aus Schönebeck bereitet sich auf das große Springturnier ihres Heimatvereins Westeregeln vor.'),
        ('05:55', 'Dein Traumjob? Zimmermann!', '', 'Vorlesen', 15, 3, 'a3', 55, 'Theo ist zehn Jahre alt, spielt gern Fußball und zeichnet gern. Außerdem steht er total auf "Sägen".'),
        ('06:10', 'Tigerenten Club', 'Der Club zum Mitmachen - Spiele, Spaß und spannendes Wissen', 'Vorlesen', 55, 3, 'a3', 55, '"krass nass!" - Das ultimative Sommer-Action-Highlight ist zurück Es wird krass nass! Spektakuläre H'),
        ('08:30', 'Alina', 'Die Pferdeflüsterin', 'Jugendserie', 60, 10, 'a10', 55, 'Alina ist verzweifelt, weil Silverado kaum Fortschritte macht. Als Patrick ihr von der Pferdeflüster'),
        ('09:30', 'Die Sendung mit der Maus', '', 'Vorlesen', 30, 6, 'a6', 55, 'Lach- und Sachgeschichten, heute mit Johannes in einem sparsamen Dorf, Trudes Tier beim Fußball-Trai'),
    ]),
    ("Sonntag, 30.08.2026", "ZDF", [
        ('06:00', 'Die Werkel-Ferkel', 'Der tiefgekühlte Wilf', 'Zeichentrick', 10, 3, 'a3', 55, 'Wegen der Hitze bauen die Werkel-Ferkel eine Eismaschine für Fred und Dana. Heimlich verfolgt Wilf d'),
        ('06:10', 'Die Werkel-Ferkel', 'Der Flatter-Schnappschuss', 'Zeichentrick', 15, 3, 'a3', 55, 'Einen Schnappschuss von einem bunten Schmetterling für Cherry machen? Das sollte doch eigentlich kei'),
        ('06:25', 'Sam & Julia im Mäusehaus', 'Das große Fondue-Fest', 'Zeichentrick', 5, 3, 'a3', 55, 'Heute ist der Jahrestag der Gründung des Mäusehauses. Das wird wie jedes Jahr mit einem großen Fondu'),
        ('06:30', 'Sam & Julia im Mäusehaus', 'Die maskierte Maus', 'Zeichentrick', 10, 3, 'a3', 55, 'Sam, Tonio und Ella sind begeisterte Fans der "Maskierten Maus", einer Heldenfigur aus dem gleichnam'),
        ('06:40', 'Sam & Julia im Mäusehaus', 'Ich bin schon groß', 'Zeichentrick', 5, 3, 'a3', 55, 'Sams kleiner Bruder Ben ist frustriert, weil er noch so klein ist und vieles noch nicht kann. Zusamm'),
        ('06:45', 'Pettersson und Findus', 'Aufruhr im Gemüsebeet', 'Zeichentrick', 15, 3, 'a3', 55, 'Pettersson glaubt, es sei doch eigentlich ganz einfach, ein Gemüsebeet einzusäen. Doch da liegt er o'),
        ('07:00', 'Wickie und die starken Männer', 'Svens Schiffbruch', 'Zeichentrick', 10, 3, 'a3', 55, 'Svens Boot ist mit Reichtümern so beladen, dass das Schiff auseinanderbricht und schließlich auf den'),
        ('07:10', 'Wickie und die starken Männer', 'Pirat Gilby', 'Zeichentrick', 15, 3, 'a3', 55, 'Wegen seiner bösen Streiche haben weder Halvar noch seine Leute Lust, Gilby mit auf große Fahrt zu n'),
        ('07:25', 'Bibi Blocksberg', 'Die Jagd nach dem Goldhexstein', 'Zeichentrick', 25, 3, 'a3', 55, 'Bibi übt Lichthexereien für die Walpurgisnacht. Der Höhepunkt ist eine Goldlicht-Hexerei der Althexe'),
        ('07:50', 'Bibi und Tina', 'Sorge um Cleopatra', 'Zeichentrick', 25, 3, 'a3', 55, 'Cleopatra, das Lieblingspferd des Grafen, ist verstört und lässt keinen mehr an sich heran. Bibi und'),
        ('08:15', 'Löwenzahn', 'Wunder des Lebens - Mit Liebe gemacht', 'Serie', 25, 6, 'a6', 55, 'Wie genau entstehen eigentlich Babys? Fritz Fuchs erforscht die folgenreiche Begegnung von Spermien '),
        ('08:40', 'Michel aus Lönneberga', 'Als Michel ein Held wurde', 'Serie', 23, 6, 'a6', 55, 'Knecht Alfred verletzt sich beim Schnitzen den Finger. Seine Schmerzen werden immer stärker. Die Swe'),
    ]),
    ("Sonntag, 30.08.2026", "SAT.1", [
        ('17:00', 'Matilda', '', 'Film', 115, 6, 'a6', 55, 'Kaum zu glauben, dass solche Eltern eine solche Tochter haben: Die kleine Matilda ist ein telekineti'),
    ]),
    ("Sonntag, 30.08.2026", "ProSieben Maxx", [
        ('04:10', 'One Piece', 'Das Bündnis der Brüder! - Die Geschichte von Ruffys und Sabos Wiederse', 'Anime', 25, 12, 'a10', 55, 'Nachdem er von Aces Tod erfahren hatte, gewann Sabo sein Gehör zurück. Zwei Jahre später besuchte er'),
        ('04:35', 'One Piece', 'Die stärkste Kreatur aller Zeiten! - Kaido der hundert Bestien', 'Anime', 20, 12, 'a10', 55, 'Kaido der hundert Bestien landet aus heiterem Himmel auf der Basis und verkündet, er werde einen Kri'),
        ('04:55', 'One Piece', 'Fujitoras nächster Schritt - Die vollständige Belagerung der Strohhüte', 'Anime', 25, 12, 'a10', 55, 'Fujitora will einen Würfel über das Schicksal von Ruffy und Law entscheiden lassen. Das Mysterium um'),
    ]),
    ("Sonntag, 30.08.2026", "WDR", [
        ('17:20', 'Wuppertal und die einzigartige Schwebebahn', '', 'Wissen', 30, 6, 'a6', 55, 'Einmal im Leben durch Wuppertal schweben! Die Wuppertaler Schwebebahn feiert ihren 125. Geburtstag -'),
    ]),
    ("Sonntag, 30.08.2026", "NDR", [
        ('04:35', 'Apple Hills', 'Cousin Walters Spielpark', 'Zeichentrick', 5, 3, 'a3', 55, 'Ein Tornado hat einen Container auf das Grundstück von Cousin Walter geworfen, und er sieht darin ei'),
        ('04:40', 'Apple Hills', 'Eine Trafalgar-Pizza, bitte!', 'Zeichentrick', 10, 3, 'a3', 55, 'In Onkel Knuts Pizzeria entdeckt Trafalgar, dass jemand eine Pizza nach Frank benannt hat. Trafalgar'),
        ('04:50', 'Apple Hills', 'Der Helmfluencer', 'Zeichentrick', 5, 3, 'a3', 55, 'Die Bürgermeisterin möchte, dass die Kinder in Apple Hills sicherer sind. Deshalb zwingt sie Frank, '),
        ('04:55', 'Apple Hills', 'Schneeball', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar und Powder haben ein Zelt aufgestellt, in dem sie die Zukunft anderer Menschen vorhersagen'),
        ('05:00', 'Apple Hills', 'Ballon-Man', 'Zeichentrick', 10, 3, 'a3', 55, 'Trafalgar lädt sich mit statischer Elektrizität auf und verwandelt sich in den Superhelden Ballon-Ma'),
        ('05:10', 'Apple Hills', 'Ironie ist nicht witzig!', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar und Powder lernen etwas über Ironie und können nicht mehr aufhören, ironisch zu sein. Der '),
        ('05:15', 'Apple Hills', 'Pulvers Präsentation', 'Zeichentrick', 5, 3, 'a3', 55, 'Alle Kinder müssen in der Schule eine Präsentation halten. Bald ist Powder an der Reihe. Die anderen'),
        ('05:20', 'Apple Hills', 'Süßigkeiten-Suppe', 'Zeichentrick', 10, 3, 'a3', 55, 'Es ist Wissenschaftstag in der Schule. Anna-Lise möchte ihr großes Idol, Professor Scharfsinn, beein'),
        ('05:30', 'Apple Hills', 'Trafalgars Entenkostüm', 'Zeichentrick', 5, 3, 'a3', 55, 'Die Klasse bekommt Besuch vom Tierfreunde-Verein, der einen Kostümwettbewerb organisiert. Trafalgar '),
        ('05:35', 'Apple Hills', 'Außerirdische im Pilzwald', 'Zeichentrick', 5, 3, 'a3', 55, 'Cousin Walter hat sich im Pilzwald verirrt! Trafalgar, Powder und Lizzie suchen ihn im Wald, wo sie '),
        ('05:40', 'Apple Hills', 'Der Trafalgar-Platz', 'Zeichentrick', 5, 3, 'a3', 55, 'Herr Zement erhält den Auftrag, die neue Touristenattraktion von Apple Hills zu bauen: den Herrn-Zem'),
        ('05:45', 'Apple Hills', 'Ein Tag mit Stiefvater', 'Zeichentrick', 10, 3, 'a3', 55, 'Powders Stiefvater muss sich um Trafalgar und Powder kümmern und möchte sie beeindrucken. Er lehrt s'),
        ('05:55', 'Apple Hills', 'Die Spielzeugkrise', 'Zeichentrick', 5, 3, 'a3', 55, 'Der Spielzeugladen in Apple Hills hat einen Wasserschaden erlitten und ist geschlossen, also beginne'),
        ('06:00', 'Apple Hills', 'Der liebenswerte Herr Zement', 'Zeichentrick', 5, 3, 'a3', 55, 'Ein harter Schlag auf den Kopf verändert Herrn Zement völlig, plötzlich ist er sehr freundlich. Er b'),
        ('06:05', 'Apple Hills', 'Das Traumspiel', 'Zeichentrick', 5, 3, 'a3', 55, 'Die Kinder haben eine wunderbare Vertretungslehrerin in der Schule, Frau Lax, die ihnen den besten S'),
        ('06:10', 'Apple Hills', 'Raketenwissenschaft', 'Zeichentrick', 10, 3, 'a3', 55, 'Eva wird große Schwester und plant eine Gender-Reveal-Party. Ganz Apple Hills ist in eine hitzige Di'),
        ('06:20', 'Apple Hills', 'Der Pfadfinder-Ausflug', 'Zeichentrick', 5, 3, 'a3', 55, 'Die Kinder aus Apple Hills sind mit der Pfadfindergruppe zum Zelten gefahren und werden die Nacht un'),
        ('06:25', 'Apple Hills', 'Stiefvaters Siegerjacke', 'Zeichentrick', 5, 3, 'a3', 55, 'Powders Stiefvater glaubt, dass er in seinem Leben nichts erreicht ha. Er beschließt, am Radrennen "'),
        ('06:30', 'Apple Hills', 'Bürgermeisterwahlen', 'Zeichentrick', 10, 3, 'a3', 55, 'Der Bürgermeisterin verlässt Apple Hills und ruft eine Neuwahl aus. Herr Zement tritt schnell als Bü'),
        ('06:40', 'Apple Hills', 'Neutags-Fest', 'Zeichentrick', 5, 3, 'a3', 55, 'Trafalgar und Powder verbringen mit dem lustigen Onkel Knut den besten Silvesterabend aller Zeiten. '),
        ('06:45', 'Edgar, das Super-Karibu', 'Super-Edgar außer Atem', 'Zeichentrick', 10, 3, 'a3', 55, 'Edgar, das Super-Karibu und Katja, die Katze, die ständig herumfaucht, versuchen die Bewohner des St'),
        ('06:55', 'Edgar, das Super-Karibu', 'Das rätselhafte Küsschen-Küsschen', 'Zeichentrick', 15, 3, 'a3', 55, 'Es ist Valentinstag in Windhausen und alle Einwohner erhalten hübsche Liebeserklärungen, die mit "Kü'),
    ]),
    ("Sonntag, 30.08.2026", "BR", [
        ('09:20', 'Die Galoschen des Glücks', '', 'Serie', 60, 6, 'a6', 55, 'Großherzogin Ottilie und ihre Diener stecken mitten in den Vorbereitungen des Geburtstags von Prinze'),
    ]),
    ("Sonntag, 30.08.2026", "MDR", [
        ('15:30', 'Hans Röckle und der Teufel', '', 'Serie', 75, 6, 'a6', 55, 'Dem Puppenspieler und Erfinder Hans Röckle erscheint der Teufel und bietet ihm einen Pakt an. Röckle'),
        ('16:45', 'Das Mädchen auf dem Besenstiel', '', 'Serie', 75, 6, 'a6', 55, 'Hexenschülerin Saxana muss 300 Jahre nachsitzen und sucht nach Abwechslung. Im Zauberlexikon stößt s'),
        ('18:52', 'Unser Sandmännchen', '', 'Serie', 8, 3, 'a3', 55, 'Pitti und Moppi spielen Feuerwehr. Rasen mit dem Handwagen quer über die Gartenbeete und stoßen alle'),
    ]),
    ("Sonntag, 30.08.2026", "RBB", [
        ('09:00', 'Das blaue Licht', '', 'Serie', 80, 6, 'a6', 55, 'Der Bauer Hans ist als Soldat in den Krieg gezogen. Zurückgekehrt und von seinem König um den Sold b'),
        ('10:20', 'Der Teufel vom Mühlenberg', '', 'Serie', 80, 6, 'a6', 55, 'Eine alte Sage berichtet, dass vor vielen 100 Jahren im Harz in einer dunklen Schlucht drei Waldgeis'),
        ('11:40', 'Die Gänsemagd', '', 'Serie', 60, 6, 'a6', 55, 'Prinzessin Elisabeth ist schon seit vielen Jahren dem Prinzen Leopold versprochen. Auf den Weg zur V'),
        ('13:50', 'Der Froschkönig', '', 'Serie', 65, 6, 'a6', 55, 'Der schönen Prinzessin fällt eines Tages beim Spielen ihre Goldkugel in den Brunnen. Traurig über de'),
        ('14:55', 'Die Gänseprinzessin', '', 'Serie', 60, 6, 'a6', 55, 'Nach Motiven der Brüder Grimm erzählt das Märchen die Geschichte eines Königreiches im Ausnahmezusta'),
        ('16:55', 'König Drosselbart', '', 'Serie', 58, 6, 'a6', 55, 'Es war einmal die stolze Prinzessin Isabella von Geranien, die war schön, aber hochmütig. Als ihr Va'),
        ('17:53', 'Unser Sandmännchen', '', 'Serie', 7, 3, 'a3', 55, 'Kallis Gute-Nacht-Geschichten: Super-Kalli'),
    ]),
    ("Sonntag, 30.08.2026", "3sat", [
        ('17:15', 'Ein Schloss am Wörthersee - Der Film', '', 'Film', 80, 6, 'a6', 55, 'Der charmante Lennie Berger hat von seinem Onkel das Schlosshotel Velden geerbt und will es auf Vord'),
    ]),
    ("Sonntag, 30.08.2026", "arte", [
        ('04:40', 'Athleticus', 'Marathonlauf', 'Zeichentrick', 35, 3, 'a3', 55, 'Die dritte Staffel des Kurzprogramms wirft einen humorvollen Blick auf unsere Gesellschaft und die R'),
    ]),
    ("Sonntag, 30.08.2026", "ORF 1", [
        ('06:00', 'Tom - Ein echter Freund', 'Tom in Südafrika', 'Zeichentrick', 25, 3, 'a3', 55, 'Rupert ist von seinem verstorbenen Onkel Rufus als Alleinerbe eingesetzt worden. Gemeinsam mit Tom u'),
        ('06:25', 'Vegesaurier', 'Was kleine Kokosnüsse brauchen', 'Zeichentrick', 5, 3, 'a3', 55, 'Ginger und die Erbs-Rexe befreien süße Kokosnussodon-Babys, die eingesperrt sind. Doch bald stellt s'),
        ('06:30', 'Servus Kasperl', 'Kasperl & Hopsi: Der kichernde Baum', 'Serie', 25, 3, 'a3', 55, 'Der Klassiker des österreichischen Kinderfernsehens mit amüsanten Kasperlstücken und vielen Möglichk'),
        ('06:55', 'Vegesaurier', 'Keinen Schritt weiter', 'Zeichentrick', 5, 3, 'a3', 55, 'Ginger und die Erbs-Rexe toben sich in der Winterlandschaft aus, als sie plötzlich auf ein kleines K'),
        ('07:00', 'Vegesaurier', 'Erbs mit Hicks', 'Zeichentrick', 5, 3, 'a3', 55, 'Ein Erbs-Rex-Baby nach dem anderen bekommt plötzlich Schluckauf. Ginger versucht den kleinen Erbs-Re'),
        ('07:05', 'Bakabu', 'Die Weltraumrakete', 'Vorlesen', 5, 3, 'a3', 55, 'Bakabu und seine Freunde fliegen mit einer Rakete in den Weltraum, dann können sie von oben auf die '),
        ('07:10', 'Knall genial', '', 'Wissen', 15, 3, 'a3', 55, 'Originelle Tipps und Tricks von Thomas Brezina und den Kids! In dieser Folge präsentieren Thomas und'),
        ('07:25', 'Der gestiefelte Kater - Abenteuer in San Lorenzo', 'Auf der Jagd', 'Serie', 25, 3, 'a3', 55, 'Mit Hut und Degen zieht der gestiefelte Kater durchs Land, immer auf der Suche nach einem neuen Aben'),
        ('07:50', 'Drunter & drüber mit Christoph Hirschler', 'Bauchreden mit Tricky Niki', 'Vorlesen', 15, 3, 'a3', 55, 'Können Socken sprechen? Mit Christophs heutigem Gast Tricky Niki geht das. Er ist Zauberer und Bauch'),
        ('08:05', 'Campsite', 'Olsok', 'Jugendserie', 10, 10, 'a10', 55, 'Die Schwestern Ronja und Anja wollen wie jedes Jahr zum Olsok-Tag Olav dem Heiligen gedenken, indem '),
        ('08:15', 'Campsite', 'Siljes Spiel', 'Jugendserie', 5, 10, 'a10', 55, 'Siljes wird langsam erwachsen und sie ist total stolz darauf, dass ihre Figur immer weiblicher wird.'),
        ('08:20', 'Campsite', 'Ein großer Fremder', 'Jugendserie', 10, 10, 'a10', 55, 'Andrine und Silje stehen beide auf Sebbe. Als Andrine Sebbe und Silje sieht, wie sie an einem Tisch '),
        ('08:30', 'Dragons - Die Wächter von Berk', 'Die Aal-Insel', 'Zeichentrick', 20, 6, 'a6', 55, 'Auf Berk sind die Aal-Pocken ausgebrochen. Die Drachenreiter müssen losziehen und Zutaten für einen '),
        ('08:50', 'Was geht?', 'Geschichten', 'Wissen', 15, 6, 'a6', 55, 'Manche Geschichten lassen uns abtauchen bis wir Raum und Zeitgefühl verlieren. Woher kommt das und h'),
        ('09:05', 'Mini Spezial', 'Schrottplatz', 'Vorlesen', 5, 6, 'a6', 55, 'Bananenschalen kommen in den Biomüll, leere Flaschen ins Altglas - was aber passiert mit alten, kapu'),
        ('09:10', 'Garfield', 'Maus TV', 'Zeichentrick', 10, 6, 'a6', 55, 'Die zwei Mäuse, die in Jons Haus wohnen, wollen ihre Sendung spät nachts nicht verpassen. Die Nageti'),
        ('09:20', 'Hallo, was machst Du?', 'Logistik', 'Wissen', 15, 6, 'a6', 55, 'Habt ihr schonmal von Intralogistik gehört? Was kompliziert klingt, schaut sich Lena heute für euch '),
        ('09:35', 'Bibi & Tina 4 - Tohuwabohu Total', '', 'Film', 110, 6, 'a6', 55, "Viertes Kinoabenteuer und turbulentes Finale der knallbunten, schwungvollen 'Bibi & Tina'-Reihe von "),
    ]),
    ("Sonntag, 30.08.2026", "SRF 1", [
        ('17:10', 'Minisguard', 'Wie macht man eigentlich Glace?', 'Serie', 15, 6, 'a6', 55, 'An einem heissen Sommertag gibt es kaum etwas Besseres als eine feine Glace. Aber wie wird Glace eig'),
    ]),
]
